import { DEVICE_FEATURE_CATEGORIES, DEVICE_FEATURE_TYPES, DEVICE_FEATURE_UNITS } from '../../../../../../server/utils/constants';

const features = {
  presence: {
    category: DEVICE_FEATURE_CATEGORIES.PRESENCE_SENSOR,
    type: DEVICE_FEATURE_TYPES.SENSOR.BINARY,
    read_only: true,
    has_feedback: false,
    min: 0,
    max: 1
  },
  door: {
    category: DEVICE_FEATURE_CATEGORIES.SIREN,
    type: DEVICE_FEATURE_TYPES.SENSOR.BINARY,
    read_only: true,
    has_feedback: false,
    min: 0,
    max: 1
  },
  water: {
    category: DEVICE_FEATURE_CATEGORIES.LEAK_SENSOR,
    type: DEVICE_FEATURE_TYPES.SENSOR.BINARY,
    read_only: true,
    has_feedback: false,
    min: 0,
    max: 1
  },
  smoke: {
    category: DEVICE_FEATURE_CATEGORIES.SMOKE_SENSOR,
    type: DEVICE_FEATURE_TYPES.SENSOR.BINARY,
    read_only: true,
    has_feedback: false,
    min: 0,
    max: 1
  },
  battery: {
    category: DEVICE_FEATURE_CATEGORIES.BATTERY,
    type: DEVICE_FEATURE_TYPES.SENSOR.INTEGER,
    read_only: true,
    has_feedback: false,
    min: 0,
    max: 100
  },
  illuminance: {
    category: DEVICE_FEATURE_CATEGORIES.LIGHT_SENSOR,
    type: DEVICE_FEATURE_TYPES.SENSOR.INTEGER,
    read_only: true,
    has_feedback: false,
    min: 0,
    max: 1000
  },
  humidity: {
    category: DEVICE_FEATURE_CATEGORIES.HUMIDITY_SENSOR,
    type: DEVICE_FEATURE_TYPES.SENSOR.INTEGER,
    unit: DEVICE_FEATURE_UNITS.PERCENT,
    read_only: true,
    has_feedback: false,
    min: 0,
    max: 100
  },
  temperature: {
    category: DEVICE_FEATURE_CATEGORIES.TEMPERATURE_SENSOR,
    type: DEVICE_FEATURE_TYPES.SENSOR.INTEGER,
    read_only: true,
    has_feedback: false,
    min: -50,
    max: 125
  },
  pressure: {
    category: DEVICE_FEATURE_CATEGORIES.PRESSURE_SENSOR,
    type: DEVICE_FEATURE_TYPES.SENSOR.INTEGER,
    read_only: true,
    has_feedback: false,
    min: 0,
    max: 10000
  },
  switch: {
    category: DEVICE_FEATURE_CATEGORIES.SWITCH,
    type: DEVICE_FEATURE_TYPES.SENSOR.BINARY,
    read_only: false,
    has_feedback: true,
    min: 0,
    max: 1
  },
  switch_sensor: {
    category: DEVICE_FEATURE_CATEGORIES.SWITCH,
    type: DEVICE_FEATURE_TYPES.SENSOR.BINARY,
    read_only: true,
    has_feedback: false,
    min: 0,
    max: 1
  },
  power: {
    category: DEVICE_FEATURE_CATEGORIES.SWITCH,
    type: DEVICE_FEATURE_TYPES.SWITCH.POWER,
    read_only: true,
    has_feedback: false,
    min: 0,
    max: 1
  },
  current: {
    category: DEVICE_FEATURE_CATEGORIES.SWITCH,
    type: DEVICE_FEATURE_TYPES.SWITCH.CURRENT,
    read_only: true,
    has_feedback: false,
    min: 0,
    max: 1000
  },
  voltage: {
    category: DEVICE_FEATURE_CATEGORIES.SWITCH,
    type: DEVICE_FEATURE_TYPES.SWITCH.VOLTAGE,
    read_only: true,
    has_feedback: false,
    min: 0,
    max: 1000
  },
  brightness: {
    category: DEVICE_FEATURE_CATEGORIES.LIGHT,
    type: DEVICE_FEATURE_TYPES.LIGHT.BRIGHTNESS,
    read_only: true,
    has_feedback: false,
    min: 0,
    max: 100
  },
  brightness: {
    category: DEVICE_FEATURE_CATEGORIES.LIGHT,
    type: DEVICE_FEATURE_TYPES.LIGHT.BRIGHTNESS,
    read_only: true,
    has_feedback: false,
    min: 0,
    max: 100
  },
  color_temperature: {
    category: DEVICE_FEATURE_CATEGORIES.LIGHT,
    type: DEVICE_FEATURE_TYPES.LIGHT.SATURATION,
    read_only: true,
    has_feedback: false,
    min: 0,
    max: 100
  },
  gas_density: {
    category: DEVICE_FEATURE_CATEGORIES.SMOKE_SENSOR,
    type: DEVICE_FEATURE_TYPES.SENSOR.INTEGER,
    read_only: true,
    has_feedback: false,
    min: 0,
    max: 1000
  },
};

const Models = {
  'WXKG01LM': [features.switch_sensor, features.battery],
  'WXKG11LM': [features.switch_sensor, features.battery],
  'WXKG12LM': [features.switch_sensor, features.battery],
  // BREAKING_IMPROVEMENT: only use sensor_click for WXKG03LM (action hold -> click hold)
  'WXKG03LM': [features.switch_sensor, features.battery, features.switch_sensor],
  'WXKG02LM': [features.switch_sensor, features.battery],
  'QBKG04LM': [features.switch, features.switch_sensor, features.switch_sensor],
  'WSDCGQ01LM': [features.temperature, features.humidity, features.battery],
  'WSDCGQ11LM': [
      features.temperature, features.humidity, features.pressure,
      features.battery,
  ],
  'RTCGQ01LM': [features.presence, features.battery],
  'RTCGQ11LM': [
      features.presence, features.illuminance,
      features.battery,
  ],
  'MCCGQ01LM': [features.door, features.battery],
  'MCCGQ11LM': [features.door, features.battery],
  'SJCGQ11LM': [features.water, features.battery],
  'MFKZQ01LM': [features.switch_sensor, features.battery],
  'ZNCZ02LM': [features.switch, features.power],
  'QBCZ11LM': [features.switch, features.power],
  'LED1545G12': [features.color_temperature],
  'LED1623G12': [features.brightness],
  'LED1622G12': [features.brightness],
  'LED1537R6': [features.color_temperature],
  'LED1650R5': [features.brightness],
  'LED1536G5': [features.color_temperature],
  '7299760PH': [features.color_temperature],
  '7146060PH': [features.color_temperature],
  '046677476816': [features.brightness],
  'F7C033': [features.brightness],
  'JTYJ-GD-01LM/BW': [features.smoke, features.battery],
  'PLUG EDP RE:DY': [features.switch, features.power],
  'SWITCH EDP RE:DY': [features.switch],
  'AA70155': [features.color_temperature],
  '4058075816718': [features.color_temperature],
  'AA69697': [features.color_temperature],
  'HALIGHTDIMWWE27': [features.brightness],
  'HALIGHTDIMWWB22': [features.brightness],
  'AB3257001NJ': [features.switch],
  '8718696449691': [features.brightness],
  'RB 185 C': [features.color_temperature],
  'BY 185 C': [features.color_temperature],
  '9290012573A': [features.color_temperature],
  'LED1624G9': [features.color_temperature],
  '73742': [features.color_temperature],
  '73740': [features.color_temperature],
  '73739': [features.color_temperature],
  '22670': [features.brightness],
  'ICTC-G-1': [features.brightness, features.battery, features.switch_sensor],
  'ICPSHC24-30EU-IL-1': [features.brightness],
  '45852GE': [features.brightness],
  'E11-G13': [features.brightness],
  'LED1649C5': [features.brightness],
  'ICPSHC24-10EU-IL-1': [features.brightness],
  'LED1546G12': [features.color_temperature],
  'L1527': [features.color_temperature],
  'L1529': [features.color_temperature],
  'L1528': [features.color_temperature],
  'L1531': [features.color_temperature],
  'RB 165': [features.brightness],
  'RB 175 W': [features.brightness],
  'RS 125': [features.brightness],
  'RS 225': [features.brightness],
  'RB 145': [features.brightness],
  'RB 245': [features.brightness],
  'PL 110': [features.brightness],
  'ST 110': [features.brightness],
  'UC 110': [features.brightness],
  'DL 110 N': [features.brightness],
  'DL 110 W': [features.brightness],
  'SL 110 N': [features.brightness],
  'SL 110 M': [features.brightness],
  'SL 110 W': [features.brightness],
  'AA68199': [features.color_temperature],
  'QBKG11LM': [features.switch, features.power, features.switch_sensor],
  'K2RGBW01': [features.color_temperature],
  '9290011370': [features.brightness],
  'DNCKATSW001': [features.switch],
  'Z809A': [features.switch, features.power],
  'NL08-0800': [features.brightness],
  '915005106701': [features.color_temperature],
  'AB32840': [features.color_temperature],
  '8718696485880': [features.color_temperature],
  '8718696598283': [features.color_temperature],
  '8718696695203': [features.color_temperature],
  '73693': [features.color_temperature],
  '324131092621': [features.switch_sensor, features.battery],
  '9290012607': [
      features.presence, features.temperature,
      features.illuminance, features.battery,
  ],
  'GL-C-008': [features.color_temperature],
  'STSS-MULT-001': [features.door, features.battery],
  'E11-G23/E11-G33': [features.brightness],
  'E1ACA4ABE38A': [features.brightness],
  'AC03645': [features.color_temperature],
  'AC03641': [features.brightness],
  'AC03648': [features.color_temperature],
  'FB56+ZSW05HG1.2': [features.switch],
  '72922-A': [features.switch],
  'AC03642': [features.color_temperature],
  'BY 165': [features.brightness],
  'ZLED-2709': [features.brightness],
  '8718696548738': [features.color_temperature],
  '4052899926110': [features.color_temperature],
  'Z01-CIA19NAE26': [features.brightness],
  'E11-N1EA': [features.color_temperature],
  '74283': [features.brightness],
  'JTQJ-BF-01LM/BW': [
      features.smoke,
      features.gas_density,
  ],
  '50043': [features.switch],
  '50045': [features.brightness],
  'AV2010/22': [features.presence, features.battery],
  '3210-L': [features.switch],
  '3320-L': [features.door],
  '3326-L': [features.presence, features.temperature],
  '7299355PH': [features.color_temperature],
  '45857GE': [features.brightness],
  'A6121': [features.door],
  '433714': [features.brightness],
  '3261030P7': [features.color_temperature],
  '3216431P5': [features.color_temperature],
  'DJT11LM': [features.switch_sensor, features.battery],
  'E1603/E1702': [features.switch],
  '7199960PH': [features.color_temperature],
  '74696': [features.brightness],
  'AB35996': [features.color_temperature],
  'AB401130055': [features.color_temperature],
  '74282': [features.color_temperature],
  'RS 128 T': [features.color_temperature],
  '53170161': [features.color_temperature],
  '4058075036147': [features.color_temperature],
  'KS-SM001': [features.switch],
  '9290002579A': [features.color_temperature],
  '4256251-RZHAC': [features.switch, features.power],
  'STS-PRS-251': [features.presence, features.battery],
  '4058075816794': [features.color_temperature],
  '4052899926158': [features.brightness],
  '4058075036185': [features.color_temperature],
  '50049': [features.color_temperature],
  '915005733701': [features.color_temperature],
  'RB 285 C': [features.color_temperature],
  '3216331P5': [features.color_temperature],
  'AC08562': [features.brightness],
  '900008-WW': [features.brightness],
  'Mega23M12': [features.color_temperature],
  'PSS-23ZBS': [features.switch],
  'HS1SA': [features.smoke, features.battery],
  'Z01-A19NAE26': [features.color_temperature],
  'AC01353010G': [features.presence, features.temperature],
  'SP 120': [features.switch, features.power],
  'RB 248 T': [features.color_temperature],
  'HS3SA': [features.smoke, features.battery],
  'HS1DS/HS3DS': [features.door],
  'HS1WL/HS3WL': [features.water],
  'HS1-WL-E': [features.water],
  '421786': [features.brightness],
  'ICZB-IW11D': [features.brightness],
  'HGZB-01A': [features.brightness],
  '3321-S': [features.door, features.temperature],
  'ZPIR-8000': [features.presence],
  'ZCTS-808': [features.door],
  'ZNLDP12LM': [features.color_temperature],
  'D1821': [features.color_temperature],
  'LTFY004': [features.color_temperature],
  'GL-S-007Z': [features.color_temperature],
  '3325-S': [features.temperature, features.presence],
  '4713407': [features.brightness],
  '464800': [features.color_temperature],
  '3261331P7': [features.color_temperature],
  '4033930P7': [features.color_temperature],
  'GL-B-008Z': [features.color_temperature],
  'AV2010/25': [features.switch, features.power],
  'E12-N14': [features.brightness],
  'RB 178 T': [features.color_temperature],
  '45856GE': [features.switch],
  'GL-D-003Z': [features.color_temperature],
  'GD-CZ-006': [features.brightness],
  'AIRAM-CTR.U': [],
  'HGZB-20-DE': [features.switch],
  'D1531': [features.brightness],
  'D1532': [features.brightness],
  'AV2010/32': [],
  'HGZB-07A': [features.color_temperature],
  'E1524': [features.switch_sensor],
  'GL-C-006/GL-C-009': [features.color_temperature],
  '100.424.11': [features.color_temperature],
  'AC0251100NJ': [features.switch_sensor, features.battery],
  '71831': [features.color_temperature],
  '404000/404005/404012': [features.color_temperature],
  '404006/404008/404004': [features.color_temperature],
  'MLI-404011': [features.switch_sensor],
  'GL-S-003Z': [features.color_temperature],
  'HS1DS-E': [features.door],
  'SP600': [features.switch, features.power],
  '1613V': [features.switch, features.power],
  'XVV-Mega23M12': [features.color_temperature],
  'GL-B-007Z': [features.color_temperature],
  '81809': [features.color_temperature],
  '4090130P7': [features.color_temperature],
  '100.110.39': [features.color_temperature],
  'SPZB0001': [],
  'HS3CG': [features.smoke],
  '81825': [features.switch_sensor],
  'Z809AF': [features.switch, features.power],
  'RADON TriTech ZB': [
      features.presence, features.temperature,
      features.battery, features.battery,
  ],
  'IM-Z3.0-DIM': [features.brightness],
  'E1746': [],
  'YRD426NRSC': [features.door, features.battery],
  'E1743': [features.switch_sensor, features.battery],
  'LED1732G11': [features.color_temperature],
  'RB 265': [features.brightness],
  '9290019758': [
      features.presence, features.temperature,
      features.illuminance, features.battery,
  ],
  'GL-FL-004TZ': [features.color_temperature],
  'IM6001-OTP05': [features.switch],
  '316GLEDRF': [features.brightness],
  'LVS-ZB500D': [features.brightness],
  'ST218': [],
  'E1525': [features.presence, features.battery],
  'ZYCT-202': [features.switch_sensor],
  '4090531P7': [features.color_temperature],
  'HGZB-42-UK / HGZB-41': [features.switch],
  'ISW-ZPR1-WP13': [
      features.presence, features.temperature,
      features.battery, features.battery,
  ],
  '9290018195': [features.brightness],
  'HGZB-04D': [features.brightness],
  'HGZB-02A': [features.brightness],
  'NCZ-3043-HA': [
      features.presence, features.temperature,
      features.battery, features.battery,
  ],
  'NCZ-3041-HA': [
      features.presence, features.temperature,
      features.battery, features.battery,
  ],
  'NCZ-3045-HA': [
      features.presence, features.temperature,
      features.battery, features.battery,
  ],
  'STS-IRM-250': [
      features.presence, features.temperature,
      features.battery, features.battery,
  ],
  '3305-S': [
      features.presence, features.temperature,
      features.battery, features.battery,
  ],
  '3300-S': [
      features.temperature, features.door,
      features.battery, features.battery,
  ],
  'IM6001-BTP01': [features.switch_sensor, features.temperature],
  'AV2010/34': [features.switch_sensor],
  'PP-WHT-US': [
      features.switch, features.power,
      features.current, features.voltage,
  ],
  'CR701-YZ': [
      features.battery, features.smoke,
      features.smoke,
  ],
  'HGZB-1S': [features.switch, features.switch_sensor],
  'HGZB-045': [features.switch, features.switch_sensor],
  'HGZB-01A/02A': [features.switch],
  'MCT-350 SMA': [features.door],
  '3310-S': [features.temperature, features.battery],
  '3315-S': [
      features.temperature, features.water,
      features.battery,
  ],
  'F-MLT-US-2': [
      features.temperature, features.door,
      features.battery, features.battery,
  ],
  'SWO-KEF1PA': [features.switch_sensor],
  'HGZB-02S': [features.switch_sensor, features.switch],
  'HGZB-41': [features.switch],
  'ZG9101SAC-HP': [features.brightness],
  'RS 122': [features.brightness],
  'GL-B-001Z': [features.color_temperature],
  'IM6001-MTP01': [
      features.temperature, features.battery,
      features.presence,
  ],
  'HLD812-Z-SC': [features.brightness],
  'HLC610-Z': [features.brightness],
  'BY 285 C': [features.color_temperature],
  'HS1RC-M': [features.switch_sensor, features.battery],
  'SWO-WDS1PA': [features.door],
  'LVS-SM10ZW': [features.door, features.battery],
  'HS2SK': [features.switch, features.power],
  '45853GE': [features.switch, features.power],
  '50064': [features.color_temperature],
  '9290011998B': [features.color_temperature],
  '4096730U7': [features.color_temperature],
  'RB 278 T': [features.brightness],
  '3315-G': [
      features.temperature, features.battery, features.water,
  ],
  'N2G-SP': [features.power, features.switch],
  'AC0363900NJ': [features.color_temperature],
  'LXZB-02A': [features.brightness],
  'GL-S-004Z': [features.color_temperature],
  'YRD226HA2619': [features.battery, features.door],
  'YMF40': [features.door],
  'V3-BTZB': [features.door],
  '3RSS008Z': [features.switch, features.battery],
  '511.10': [features.brightness],
  'IM6001-MPP01': [
      features.temperature, features.door, features.battery,
  ],
  'HLC821-Z-SC': [features.brightness],
  'RS 228 T': [features.color_temperature],
  '67200BL': [features.switch],
  '2430-100': [features.switch_sensor],
  '100.425.90': [features.switch],
  '74580': [features.brightness],
  'HS1CA-E': [
      features.smoke, features.battery,
      features.battery,
  ],
  'MCT-340 E': [features.door],
  'D1542': [features.color_temperature],
  'ZGRC-KEY-013': [features.switch_sensor],
  'ZigUP': [features.switch],
  'YRD256HA20BP': [features.battery, features.door],
  'SZ-ESW01-AU': [features.power, features.switch],
  'PSM-29ZBSR': [features.switch],
  'ZM350STW1TCF': [features.color_temperature],
  'M350STW1': [features.brightness],
  'A806S-Q1R': [features.brightness],
  'XY12S-15': [features.color_temperature],
  'B07KG5KF5R': [features.color_temperature],
  'HEIMAN-M1': [features.door],
  '3216131P5': [features.color_temperature],
  'ST8AU-CON': [features.brightness],
  'HS3MS': [features.presence],
  'NCZ-3011-HA': [
      features.presence, features.humidity, features.temperature,
  ],
  'MEAZON_BIZY_PLUG': [features.power, features.switch, features.temperature],
  'MEAZON_DINRAIL': [features.power, features.switch, features.temperature],
  'HS1CA-M': [features.smoke, features.battery],
  '7099860PH': [features.color_temperature],
  'HV-GSCXZB269': [features.color_temperature],
  '3216231P5': [features.color_temperature],
  'AC03647': [features.color_temperature],
  '421792': [features.color_temperature],
  'HGZB-06A': [features.color_temperature],
  'LED1733G7': [features.color_temperature],
  '9290011370B': [features.brightness],
  'RB 250 C': [features.color_temperature],
  '8718696170625': [features.brightness],
  'GL-G-001Z': [features.color_temperature],
  'HV-GSCXZB279_HV-GSCXZB229': [features.color_temperature],
  'HS2WD-E': [features.battery],
  'ZNMS12LM': [
      features.switch_sensor, features.door,
  ],
  '12050': [features.switch, features.power],
  'ROB_200-004-0': [features.brightness],
  'RH3040': [features.battery, features.presence],
};

export default Models;
