const CONFIGURATION = {
  MATTERBRIDGE_PORT_VALUE: '8283',
  MATTERBRIDGE_PORT: 'MATTERBRIDGE_PORT',
  DOCKER_MATTERBRIDGE_VERSION: 'DOCKER_MATTERBRIDGE_VERSION',
  MATTERBRIDGE_CONTAINER_NAME: 'MATTERBRIDGE_CONTAINER_NAME', // Persisted name of the Matterbridge container we own
};

const DEFAULT = {
  DOCKER_MATTERBRIDGE_VERSION: '1',
  CONFIGURATION_PATH: 'matterbridge',
};

module.exports = {
  CONFIGURATION,
  DEFAULT,
};
