// Best-effort mapping from an emoji to an icon of the shared icon set
// (server/config/icons.json). Emojis render differently on every platform,
// so the UI never displays them as icons directly: it translates them to
// the matching feather glyph instead, and gives up (returns null) rather
// than guessing when there is no close match.
// Keys are stored fully unqualified (no U+FE0F variation selector, no skin
// tone): lookups normalize the input the same way, so "🛋️" and "🛋" both hit.
const EMOJI_ICONS = {
  // homes & buildings
  '🏠': 'home',
  '🏡': 'home',
  '🏘': 'home',
  '🏚': 'home',
  '🛖': 'home',
  '🏢': 'building',
  '🏬': 'building',
  '🏦': 'building',
  '🏰': 'building',
  '🏯': 'building',
  '🏭': 'warehouse',
  '🏥': 'stethoscope',
  '⛺': 'caravan',
  '🏕': 'caravan',
  '🛻': 'truck',

  // rooms & furniture
  '🛋': 'sofa',
  '🪑': 'armchair',
  '🛏': 'bed',
  '🛌': 'bed',
  '😴': 'bed',
  '💤': 'bed',
  '🚪': 'door-closed',
  '🪟': 'blinds',
  '🚽': 'toilet',
  '🧻': 'toilet',
  '🛁': 'bath',
  '🚿': 'shower-head',
  '🖼': 'image',
  '📦': 'package',

  // kitchen & food
  '🍳': 'cooking-pot',
  '🥘': 'cooking-pot',
  '🫕': 'cooking-pot',
  '🍽': 'utensils',
  '🍴': 'utensils',
  '🥄': 'utensils',
  '🔪': 'utensils',
  '🍕': 'pizza',
  '🍔': 'sandwich',
  '🥪': 'sandwich',
  '🥐': 'croissant',
  '🥗': 'salad',
  '🥕': 'carrot',
  '🍎': 'apple',
  '🥛': 'milk',
  '🥚': 'egg',
  '🎂': 'cake',
  '🍰': 'cake-slice',
  '🍦': 'ice-cream-cone',
  '🍿': 'popcorn',
  '☕': 'coffee',
  '🍺': 'beer',
  '🍻': 'beer',
  '🍷': 'wine',
  '🥂': 'wine',
  '🍸': 'wine',
  '🥤': 'cup-soda',
  '🍹': 'cup-soda',

  // appliances & cleaning
  '🧺': 'washing-machine',
  '🧹': 'brush-cleaning',
  '🧽': 'brush-cleaning',
  '🧼': 'brush-cleaning',
  '🫧': 'droplets',
  '💧': 'droplet',
  '🚰': 'droplet',
  '⛲': 'droplets',
  '🧊': 'snowflake',
  '❄': 'snowflake',
  '🔥': 'flame',
  '🕯': 'flame-kindling',
  '♨': 'heater',
  '🌡': 'thermometer',
  '🥵': 'thermometer-sun',
  '🥶': 'thermometer-snowflake',
  '🌀': 'fan',
  '🗑': 'trash-2',
  '♻': 'recycle',
  '🚮': 'trash',

  // media & devices
  '📺': 'tv',
  '📽': 'projector',
  '🎬': 'clapperboard',
  '🎞': 'film',
  '🎥': 'video',
  '📹': 'video',
  '📷': 'camera',
  '📸': 'camera',
  '📻': 'radio',
  '🎙': 'mic',
  '🎤': 'mic-vocal',
  '🎧': 'headphones',
  '🔈': 'volume',
  '🔉': 'volume-1',
  '🔊': 'volume-2',
  '📢': 'volume-2',
  '🔇': 'volume-x',
  '🎵': 'music',
  '🎶': 'music',
  '🎼': 'music-2',
  '🎸': 'music-2',
  '🎹': 'music-2',
  '🎻': 'music-2',
  '🎺': 'music-2',
  '🥁': 'music-2',
  '🖥': 'monitor',
  '💻': 'laptop',
  '⌨': 'keyboard',
  '🖨': 'printer',
  '📱': 'smartphone',
  '☎': 'phone',
  '📞': 'phone',
  '⌚': 'watch',
  '🕹': 'gamepad',
  '🎮': 'gamepad-2',
  '🎲': 'gamepad-2',
  '💾': 'save',
  '💿': 'disc',
  '📀': 'disc',
  '🧠': 'brain',
  '🤖': 'bot',
  '📡': 'satellite-dish',
  '🛰': 'satellite-dish',
  '📶': 'wifi',
  '🛜': 'wifi',
  '🌐': 'globe',

  // energy, light & network
  '🔌': 'plug',
  '🔋': 'battery',
  '🪫': 'battery-low',
  '⚡': 'zap',
  '💡': 'lightbulb',
  '🔦': 'flashlight',
  '🏮': 'lamp',
  '🔆': 'sun-medium',
  '🔅': 'sun-dim',

  // security
  '🔔': 'bell',
  '🛎': 'bell',
  '🔕': 'bell-off',
  '🚨': 'siren',
  '🚑': 'siren',
  '🚒': 'siren',
  '🚓': 'siren',
  '🧯': 'alarm-smoke',
  '🔒': 'lock',
  '🔓': 'unlock',
  '🔐': 'lock-keyhole',
  '🔑': 'key',
  '🗝': 'key-round',
  '🛡': 'shield',
  '👁': 'eye',
  '🕵': 'eye',

  // tools & settings
  '🎛': 'sliders-horizontal',
  '🎚': 'sliders',
  '⚙': 'settings',
  '🔧': 'wrench',
  '🪛': 'wrench',
  '🔨': 'hammer',
  '🚧': 'hammer',
  '🛠': 'toolbox',
  '🧰': 'toolbox',
  '📏': 'ruler',
  '📐': 'ruler',
  '✂': 'scissors',
  '🎨': 'paintbrush',
  '🖌': 'paintbrush',

  // health & sport
  '🧪': 'pipette',
  '🔬': 'pipette',
  '💊': 'pill',
  '🩺': 'stethoscope',
  '❤': 'heart',
  '💖': 'heart',
  '💕': 'heart',
  '🫀': 'heart-pulse',
  '💪': 'dumbbell',
  '🏋': 'dumbbell',
  '🚴': 'bike',
  '🚲': 'bike',
  '🏃': 'activity',
  '⚽': 'activity',
  '🏀': 'activity',
  '🎾': 'activity',
  '🧘': 'person-standing',
  '👟': 'footprints',
  '🏊': 'waves',

  // weather & sky
  '☀': 'sun',
  '🌞': 'sun',
  '🌤': 'cloud-sun',
  '⛅': 'cloud-sun',
  '🌥': 'cloud-sun',
  '☁': 'cloud',
  '🌧': 'cloud-rain',
  '🌦': 'cloud-sun-rain',
  '⛈': 'cloud-lightning',
  '🌩': 'cloud-lightning',
  '🌨': 'cloud-snow',
  '🌫': 'cloud-fog',
  '🌪': 'tornado',
  '🌈': 'rainbow',
  '🌬': 'wind',
  '💨': 'wind',
  '🌊': 'waves',
  '☔': 'umbrella',
  '🌂': 'umbrella',
  '⛱': 'umbrella',
  '🏖': 'umbrella',
  '🌙': 'moon',
  '🌛': 'moon',
  '🌜': 'moon',
  '🌚': 'moon',
  '🌝': 'moon',
  '🌕': 'moon',
  '🌑': 'moon',
  '⭐': 'star',
  '🌟': 'star',
  '🔭': 'star',
  '✨': 'sparkles',
  '🌍': 'globe',
  '🌎': 'globe',
  '🌏': 'globe',
  '🗺': 'map',
  '🧭': 'compass',
  '📍': 'map-pin',
  '🌅': 'sunrise',
  '🌄': 'sunrise',
  '🌇': 'sunset',
  '🌆': 'sunset',

  // garden & nature
  '🌱': 'sprout',
  '🪴': 'sprout',
  '🌵': 'sprout',
  '🌿': 'leaf',
  '☘': 'leaf',
  '🍀': 'leaf',
  '🍃': 'leaf',
  '🍁': 'leaf',
  '🍂': 'leaf',
  '🌳': 'tree-deciduous',
  '🌲': 'tree-pine',
  '🎄': 'tree-pine',
  '🏔': 'tree-pine',
  '⛰': 'tree-pine',
  '🌴': 'trees',
  '🏝': 'trees',
  '🌻': 'flower',
  '🌼': 'flower',
  '🌸': 'flower-2',
  '🌺': 'flower-2',
  '🌷': 'flower-2',
  '💐': 'flower-2',
  '🚜': 'tractor',
  '🧑‍🌾': 'tractor',
  '👨‍🌾': 'tractor',
  '👩‍🌾': 'tractor',

  // people & pets
  '👤': 'user',
  '👨': 'user',
  '👩': 'user',
  '🧑': 'user',
  '👥': 'users',
  '👪': 'users',
  '👶': 'baby',
  '🍼': 'baby',
  '🚼': 'baby',
  '👧': 'baby',
  '👦': 'baby',
  '🧒': 'baby',
  '🧸': 'baby',
  '🧑‍🍳': 'chef-hat',
  '👨‍🍳': 'chef-hat',
  '👩‍🍳': 'chef-hat',
  '🧑‍🔧': 'wrench',
  '👨‍🔧': 'wrench',
  '👩‍🔧': 'wrench',
  '🐶': 'dog',
  '🐕': 'dog',
  '🦮': 'dog',
  '🐩': 'dog',
  '🐱': 'cat',
  '🐈': 'cat',
  '🐾': 'paw-print',
  '🐹': 'paw-print',
  '🐭': 'paw-print',
  '🐦': 'bird',
  '🐤': 'bird',
  '🦜': 'bird',
  '🐰': 'rabbit',
  '🐇': 'rabbit',
  '🐢': 'turtle',
  '🐟': 'fish',
  '🐠': 'fish',
  '🎣': 'fish',
  '🐿': 'squirrel',
  '🦴': 'bone',

  // transport
  '🚗': 'car',
  '🚙': 'car',
  '🏎': 'car',
  '🚘': 'car-front',
  '🚚': 'truck',
  '🚛': 'truck',
  '🚌': 'bus',
  '🚐': 'bus',
  '🏍': 'bike',
  '🛵': 'bike',
  '🛴': 'bike',
  '🚂': 'train-front',
  '🚆': 'train-front',
  '🚄': 'train-front',
  '🚇': 'train-front',
  '✈': 'plane',
  '🛫': 'plane',
  '🛬': 'plane',
  '🚀': 'plane',
  '⛵': 'ship',
  '🚢': 'ship',
  '🛥': 'ship',
  '⚓': 'anchor',
  '⛽': 'fuel',
  '🅿': 'parking-meter',
  '🛣': 'route',

  // office, money & everyday life
  '💼': 'briefcase',
  '🧳': 'briefcase',
  '🎒': 'backpack',
  '📚': 'book-open',
  '📖': 'book-open',
  '📕': 'book',
  '✏': 'edit',
  '📝': 'edit',
  '🖊': 'edit-2',
  '🖋': 'edit-2',
  '📄': 'file-text',
  '📰': 'file-text',
  '📁': 'folder',
  '🗂': 'folder',
  '📅': 'calendar',
  '📆': 'calendar',
  '🗓': 'calendar-days',
  '⏰': 'alarm-clock',
  '⏱': 'timer',
  '⏲': 'timer',
  '🕰': 'clock',
  '🕐': 'clock',
  '⌛': 'hourglass',
  '⏳': 'hourglass',
  '📈': 'trending-up',
  '💹': 'trending-up',
  '📉': 'trending-down',
  '📊': 'bar-chart',
  '💰': 'banknote',
  '💵': 'banknote',
  '💶': 'euro',
  '💲': 'dollar-sign',
  '🪙': 'banknote',
  '💳': 'credit-card',
  '🐷': 'piggy-bank',
  '👛': 'wallet',
  '🛒': 'shopping-cart',
  '🛍': 'shopping-bag',
  '🧾': 'receipt',
  '🎁': 'gift',
  '🎉': 'party-popper',
  '🎊': 'party-popper',
  '🎈': 'party-popper',
  '📬': 'mailbox',
  '📫': 'mailbox',
  '📪': 'mailbox',
  '📮': 'mailbox',
  '✉': 'mail',
  '📧': 'mail',
  '🔍': 'search',
  '🔎': 'search',
  '🎯': 'target',
  '🏆': 'award',
  '🥇': 'award',
  '🎓': 'graduation-cap',
  '👕': 'shirt',
  '👔': 'shirt',
  '👗': 'shirt',
  '🧦': 'shirt',
  '👓': 'glasses',
  '🕶': 'glasses',
  '📎': 'paperclip',
  '🔗': 'link',

  // signs
  '🚫': 'ban',
  '⛔': 'ban',
  '🚭': 'ban',
  '❌': 'x',
  '✅': 'check',
  '✔': 'check',
  '☑': 'check-square',
  '❓': 'help-circle',
  '❗': 'alert-circle',
  '⚠': 'alert-triangle',
  '🆘': 'life-buoy'
};

const NORMALIZE_REGEX = /\uFE0F|\p{Emoji_Modifier}/gu;
const FLAG_REGEX = /^\p{Regional_Indicator}{2}$/u;

/**
 * Returns the icon of the shared icon set matching an emoji, or null when
 * there is no close match.
 * @param {string} emoji - A single emoji (possibly a ZWJ sequence).
 * @returns {string|null} - The icon name, or null.
 * @example
 * iconFromEmoji('🎬'); // 'clapperboard'
 */
export const iconFromEmoji = emoji => {
  if (!emoji) {
    return null;
  }
  const normalized = emoji.replace(NORMALIZE_REGEX, '');
  if (EMOJI_ICONS[normalized]) {
    return EMOJI_ICONS[normalized];
  }
  if (FLAG_REGEX.test(normalized)) {
    return 'flag';
  }
  // Unknown ZWJ sequence: the base glyph usually carries the meaning (any
  // person-based sequence falls back to the person mapping), except a
  // family \u2014 several person glyphs joined \u2014 which maps to the group icon
  const parts = normalized.split('\u200D');
  const persons = parts.filter(part => EMOJI_ICONS[part] === 'user' || EMOJI_ICONS[part] === 'baby').length;
  if (persons > 1) {
    return 'users';
  }
  return EMOJI_ICONS[parts[0]] || null;
};
