# We provide a way to help Gladys Assistant financially: Gladys Plus.
# It's a package which gives the user additional features, at a 9.99€/month price.
#
# It's thanks to these contributions that this project can be sustainable, so thank you if you helped :)

custom: ['https://gladysassistant.com']
