coverage:
  status:
    project:
      default:
        target: 90% #overall project/ repo coverage
      front:
        target: 60%
        flags:
          - front
      server:
        target: 90%
        flags:
          - server

# adding Flags to your `layout` configuration to show up in the PR comment
comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  branches: null

# New root YAML section = `flags:`
# This is where you would define every flag from your
# uploader, and update when new Flags added

flags:
  front:
    paths:
      - front
    carryforward: true
  server:
    paths:
      - server
    carryforward: true
