const DEVICE_SERVICE_ID = 'yeelight';
const DEVICE_EXTERNAL_ID_BASE = 'yeelight';
const DEVICE_IP_ADDRESS = 'IP_ADDRESS';
const DEVICE_PORT_ADDRESS = 'PORT_ADDRESS';

module.exports = {
  DEVICE_SERVICE_ID,
  DEVICE_EXTERNAL_ID_BASE,
  DEVICE_IP_ADDRESS,
  DEVICE_PORT_ADDRESS,
};
