const { DEVICE_FEATURE_CATEGORIES, DEVICE_FEATURE_TYPES } = require('../../../utils/constants');

const ENERGY_INDEX_FEATURE_TYPES = {
  [DEVICE_FEATURE_CATEGORIES.ENERGY_SENSOR]: [
    DEVICE_FEATURE_TYPES.ENERGY_SENSOR.INDEX,
    DEVICE_FEATURE_TYPES.ENERGY_SENSOR.ENERGY,
  ],
  [DEVICE_FEATURE_CATEGORIES.SWITCH]: [DEVICE_FEATURE_TYPES.SWITCH.ENERGY],
};

module.exports = {
  ENERGY_INDEX_FEATURE_TYPES,
};
