const VARIABLES = {
  MATTER_ENABLED: 'MATTER_ENABLED',
  MATTER_BACKUP: 'MATTER_BACKUP',
};

const MATTER_NODE_CONNECTION_TIMEOUT_MS = 15000;
const MATTER_NODE_REFRESH_CONCURRENCY = 3;

module.exports = {
  VARIABLES,
  MATTER_NODE_CONNECTION_TIMEOUT_MS,
  MATTER_NODE_REFRESH_CONCURRENCY,
};
