import { Text, Localizer, MarkupText } from 'preact-i18n';
import cx from 'classnames';

const StockExchangePage = ({ children, ...props }) => (
  <div class="page">
    <div class="page-main">
      <div class="my-3 my-md-5">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="card">
                <div class="card-body">
                  <div
                    class={cx('dimmer', {
                      active: props.loading
                    })}
                  >
                    <div class="loader" />
                    <div class="dimmer-content">
                      <h2>
                        <Text id="integration.stockExchange.title" />
                      </h2>
                      <p>
                        <MarkupText id="integration.stockExchange.introduction" />
                      </p>
                      <p>
                        <MarkupText id="integration.stockExchange.instructions" />
                      </p>

                      <div class="form-group">
                        <div class="form-label">
                          <Text id="integration.stockExchange.apiKeyLabel" />
                        </div>
                        <div class="input-group">
                          <Localizer>
                            <input
                              type="text"
                              class="form-control"
                              name="stockExchangeApiKey"
                              placeholder={<Text id="integration.stockExchange.apiKeyPlaceholder" />}
                              onInput={props.updateConfiguration}
                              value={props.stockExchangeApiKey}
                            />
                          </Localizer>

                        </div>
                      </div>


                      <div class="form-group">
                        <div class="form-label">
                          <Text id="integration.stockExchange.selectTickerLabel" />
                        </div>
                        <Text id="integration.stockExchange.selectTickerDescription" />
                        <select
                          class="form-control"
                          onChange={props.updateConfiguration}
                          name="stockExchangeTickers"
                          value={props.stockExchangeTickers}>
                          <option value="^FCHI">
                            CAC40
                          </option>
                          <option value="GIB">
                            CGI
                          </option>
                          <option value="ALMIL.PA">1000MERCIS</option>
                          <option value="2CRSI.PA">2CRSI</option>
                          <option value="MLATV.PA">A TOUTE VITESSE</option>
                          <option value="ASP.PA">A.S.T. GROUPE</option>
                          <option value="AB.PA">AB SCIENCE</option>
                          <option value="ABCA.PA">ABC ARBITRAGE</option>
                          <option value="ABEO.PA">ABEO</option>
                          <option value="ABNX.PA">ABIONYX PHARMA</option>
                          <option value="ABVX.PA">ABIVAX</option>
                          <option value="ACAN.PA">ACANTHE DEV.</option>
                          <option value="AC.PA">ACCOR</option>
                          <option value="ALALO.PA">ACHETER-LOUER.FR</option>
                          <option value="EOS.PA">ACTEOS</option>
                          <option value="ATI.PA">ACTIA GROUP</option>
                          <option value="ALACT.PA">ACTIPLAY (GROUPE)</option>
                          <option value="MLACT.PA">ACTIVIUM GROUP</option>
                          <option value="ALADA.PA">ADA</option>
                          <option value="ALDV.PA">ADC SIIC</option>
                          <option value="ALARF.PA">ADEUNIS</option>
                          <option value="ALP.PA">ADL PARTNER</option>
                          <option value="ADOC.PA">ADOCIA</option>
                          <option value="ALADO.PA">ADOMOS</option>
                          <option value="ADP.PA">ADP</option>
                          <option value="ALADM.PA">ADTHINK</option>
                          <option value="ADUX.PA">ADUX</option>
                          <option value="ADV.PA">ADVENIS</option>
                          <option value="ADVIC.PA">ADVICENNE</option>
                          <option value="ADVI.PA">ADVINI</option>
                          <option value="AKOM.PA">AERKOMM INC</option>
                          <option value="MLAGI.PA">AG3I</option>
                          <option value="MLAGP.PA">AGP MALAGA SOCIMI</option>
                          <option value="ALAGP.PA">AGRIPOWER</option>
                          <option value="ALAGR.PA">AGROGENERATION</option>
                          <option value="AF.PA">AIR FRANCE -KLM</option>
                          <option value="AI.PA">AIR LIQUIDE</option>
                          <option value="MLAIM.PA">AIR MARINE</option>
                          <option value="AIR.PA">AIRBUS</option>
                          <option value="AKA.PA">AKKA TECHNOLOGIES</option>
                          <option value="AKW.PA">AKWEL</option>
                          <option value="ABIO.PA">ALBIOMA</option>
                          <option value="ALCHI.PA">ALCHIMIE</option>
                          <option value="ALD.PA">ALD</option>
                          <option value="ALPHY.PA">ALES GROUPE</option>
                          <option value="CDA.PA">ALPES (COMPAGNIE)</option>
                          <option value="ALM.PA">ALPHA MOS</option>
                          <option value="ALO.PA">ALSTOM</option>
                          <option value="ALODS.PA">ALSTOM DS</option>
                          <option value="LTA.PA">ALTAMIR</option>
                          <option value="ALTA.PA">ALTAREA</option>
                          <option value="AREIT.PA">ALTAREIT</option>
                          <option value="ATE.PA">ALTEN</option>
                          <option value="ALTUR.PA">ALTUR INVEST.</option>
                          <option value="MLALV.PA">ALVEEN</option>
                          <option value="MLAAH.PA">AMATHEON AGRI</option>
                          <option value="ALMIB.PA">AMOEBA</option>
                          <option value="AMPLI.PA">AMPLITUDE SURGICAL</option>
                          <option value="AMUN.PA">AMUNDI</option>
                          <option value="ALANV.PA">ANEVIA</option>
                          <option value="ANVBS.PA">ANEVIA BSA 2018</option>
                          <option value="ANVBU.PA">ANEVIA BSA A</option>
                          <option value="ANVBV.PA">ANEVIA BSA B</option>
                          <option value="ALANT.PA">ANTEVENIO</option>
                          <option value="APAM.PA">APERAM</option>
                          <option value="APM.PA">APTORUM GROUP CL A</option>
                          <option value="ALAQU.PA">AQUILA</option>
                          <option value="MT.PA">ARCELORMITTAL SA</option>
                          <option value="JXR.PA">ARCHOS</option>
                          <option value="ALCUR.PA">ARCURE</option>
                          <option value="MLARD.PA">ARDOIN ST AMAND A</option>
                          <option value="ARDO.PA">ARDOIN ST AMAND B</option>
                          <option value="ARG.PA">ARGAN</option>
                          <option value="AKE.PA">ARKEMA</option>
                          <option value="MLARO.PA">AROCA DEL PINAR</option>
                          <option value="ARTE.PA">ARTEA</option>
                          <option value="ALATF.PA">ARTEFACT</option>
                          <option value="PRC.PA">ARTMARKET COM</option>
                          <option value="ARTO.PA">ARTOIS NOM.</option>
                          <option value="MLAEM.PA">ASHLER ET MANSON</option>
                          <option value="ASIT.PA">ASIT</option>
                          <option value="ASY.PA">ASSYSTEM</option>
                          <option value="ATA.PA">ATARI</option>
                          <option value="ATEME.PA">ATEME</option>
                          <option value="ATO.PA">ATOS</option>
                          <option value="AUB.PA">AUBAY</option>
                          <option value="MLAUD.PA">AUDIENCE LABS</option>
                          <option value="ALAVY.PA">AUDIOVALLEY</option>
                          <option value="AUGR.PA">AUGROS COSMETICS</option>
                          <option value="ALAMG.PA">AUPLATA MINING GR</option>
                          <option value="AURE.PA">AUREA</option>
                          <option value="AURS.PA">AURES TECHNOLOGIES</option>
                          <option value="AVT.PA">AVENIR TELECOM</option>
                          <option value="CS.PA">AXA</option>
                          <option value="AXW.PA">AXWAY SOFTWARE</option>
                          <option value="MLAZL.PA">AZ LEASING</option>
                          <option value="MLAAT.PA">AZOREAN TECH</option>
                          <option value="BCRA.PA">BACCARAT</option>
                          <option value="ALBKK.PA">BAIKOWSKI</option>
                          <option value="BAIN.PA">BAINS MER MONACO</option>
                          <option value="BALYO.PA">BALYO</option>
                          <option value="BUI.PA">BARBARA BUI</option>
                          <option value="MLBAR.PA">BARINGS CORE SPAIN</option>
                          <option value="BASS.PA">BASSAC</option>
                          <option value="BLC.PA">BASTIDE LE CONFORT</option>
                          <option value="MLBAT.PA">BATLA MINERALS</option>
                          <option value="ALBDM.PA">BD MULTI MEDIA</option>
                          <option value="FBEL.PA">BEL</option>
                          <option value="BEN.PA">BENETEAU</option>
                          <option value="ALDBL.PA">BERNARD LOISEAU</option>
                          <option value="BB.PA">BIC</option>
                          <option value="BIG.PA">BIGBEN INTERACTIVE</option>
                          <option value="ALBLD.PA">BILENDI</option>
                          <option value="ALTUV.PA">BIO-UV GROUP</option>
                          <option value="ALCOR.PA">BIOCORP</option>
                          <option value="BIM.PA">BIOMERIEUX</option>
                          <option value="ALBPS.PA">BIOPHYTIS</option>
                          <option value="BPSBS.PA">BIOPHYTIS BSA</option>
                          <option value="ALBIO.PA">BIOSYNEX</option>
                          <option value="BIOBS.PA">BIOSYNEX BSAR</option>
                          <option value="BLEE.PA">BLEECKER</option>
                          <option value="MLBSP.PA">BLUE SHARK POWER</option>
                          <option value="ALBLU.PA">BLUELINEA</option>
                          <option value="BLUBS.PA">BLUELINEA BSA J</option>
                          <option value="BLUBT.PA">BLUELINEA BSA Y</option>
                          <option value="BNP.PA">BNP PARIBAS ACT.A</option>
                          <option value="MLONE.PA">BODY ONE</option>
                          <option value="BOI.PA">BOIRON</option>
                          <option value="BOL.PA">BOLLORE</option>
                          <option value="BON.PA">BONDUELLE</option>
                          <option value="BOTHE.PA">BONE THERAPEUTICS</option>
                          <option value="BOOST.PA">BOOSTHEAT</option>
                          <option value="ALBOU.PA">BOURRELIER GROUP</option>
                          <option value="BSD.PA">BOURSE DIRECT</option>
                          <option value="EN.PA">BOUYGUES</option>
                          <option value="BVI.PA">BUREAU VERITAS</option>
                          <option value="BUR.PA">BURELLE</option>
                          <option value="CAT31.PA">CA TOULOUSE 31 CCI</option>
                          <option value="ALCG.PA">CABASSE GROUP</option>
                          <option value="CAFO.PA">CAFOM</option>
                          <option value="MLAAE.PA">CAIRE</option>
                          <option value="CBDG.PA">CAMBODGE NOM.</option>
                          <option value="CAPLI.PA">CAPELLI</option>
                          <option value="CAP.PA">CAPGEMINI</option>
                          <option value="ALCRB.PA">CARBIOS</option>
                          <option value="ALCAR.PA">CARMAT</option>
                          <option value="CARM.PA">CARMILA</option>
                          <option value="CARP.PA">CARPINIENNE PART.</option>
                          <option value="CA.PA">CARREFOUR</option>
                          <option value="CO.PA">CASINO GUICHARD</option>
                          <option value="CAS.PA">CAST</option>
                          <option value="CATG.PA">CATANA GROUP</option>
                          <option value="CTRG.PA">CATERING INTL SCES</option>
                          <option value="CATR.PA">CATERPILLAR INC</option>
                          <option value="CBOT.PA">CBO TERRITORIA</option>
                          <option value="MLCEC.PA">CECURITY.COM</option>
                          <option value="CGM.PA">CEGEDIM</option>
                          <option value="CGR.PA">CEGEREAL</option>
                          <option value="ALCLS.PA">CELLECTIS</option>
                          <option value="CYAD.PA">CELYAD ONCOLOGY</option>
                          <option value="ALPCV.PA">CERINNOV GROUP</option>
                          <option value="ALCES.PA">CESAR</option>
                          <option value="MLCSA.PA">CESYNT A SHARES</option>
                          <option value="MLCSB.PA">CESYNT B SHARES</option>
                          <option value="CFI.PA">CFI</option>
                          <option value="MLCFM.PA">CFM INDOSUEZWEALTH</option>
                          <option value="CGG.PA">CGG</option>
                          <option value="CGGBS.PA">CGG BSA 1</option>
                          <option value="CGGBT.PA">CGG BSA 2</option>
                          <option value="MLCFD.PA">CH.FER DEPARTEMENT</option>
                          <option value="MLCVG.PA">CH.FER VAR GARD N.</option>
                          <option value="CRI.PA">CHARGEURS</option>
                          <option value="CHSR.PA">CHAUSSERIA</option>
                          <option value="MLCHE.PA">CHEOPS TECHNOLOGY</option>
                          <option value="CDI.PA">CHRISTIAN DIOR</option>
                          <option value="CIBBS.PA">CIBOX BS</option>
                          <option value="CIB.PA">CIBOX INTER A CTIV</option>
                          <option value="MLCMB.PA">CIE DU MONT BLANC</option>
                          <option value="MLCIO.PA">CIOA</option>
                          <option value="CLA.PA">CLARANOVA</option>
                          <option value="ALCLA.PA">CLASQUIN</option>
                          <option value="COM.PA">CNIM GROUP</option>
                          <option value="CNV.PA">CNOVA</option>
                          <option value="CNP.PA">CNP ASSURANCES</option>
                          <option value="COFA.PA">COFACE</option>
                          <option value="ALCOF.PA">COFIDUR</option>
                          <option value="COGEC.PA">COGELEC</option>
                          <option value="ALCOG.PA">COGRA</option>
                          <option value="COH.PA">COHERIS</option>
                          <option value="ALCOI.PA">COIL</option>
                          <option value="RE.PA">COLAS</option>
                          <option value="MLCLP.PA">COLIPAYS</option>
                          <option value="MLMFI.PA">CONDOR TECHNOLOG</option>
                          <option value="MLCNT.PA">CONSORT NT</option>
                          <option value="MLLCB.PA">CONSTRUCTEURS BOIS</option>
                          <option value="MLCOR.PA">COREP LIGHTING</option>
                          <option value="MLCOU.PA">COURBET</option>
                          <option value="COUR.PA">COURTOIS</option>
                          <option value="COV.PA">COVIVIO</option>
                          <option value="COVH.PA">COVIVIO HOTELS</option>
                          <option value="CRAP.PA">CRCAM ALP.PROV.CCI</option>
                          <option value="CRAV.PA">CRCAM ATL.VEND.CCI</option>
                          <option value="CRBP2.PA">CRCAM BRIE PIC2CCI</option>
                          <option value="CIV.PA">CRCAM ILLE-VIL.CCI</option>
                          <option value="CRLA.PA">CRCAM LANGUED CCI</option>
                          <option value="CRLO.PA">CRCAM LOIRE HTE L.</option>
                          <option value="CMO.PA">CRCAM MORBIHAN CCI</option>
                          <option value="CNF.PA">CRCAM NORD CCI</option>
                          <option value="CCN.PA">CRCAM NORM.SEINE</option>
                          <option value="CAF.PA">CRCAM PARIS ET IDF</option>
                          <option value="CRSU.PA">CRCAM SUD R.A.CCI</option>
                          <option value="CRTO.PA">CRCAM TOURAINE CCI</option>
                          <option value="ACA.PA">CREDIT AGRICOLE</option>
                          <option value="ALCJ.PA">CROSSJECT</option>
                          <option value="CROS.PA">CROSSWOOD</option>
                          <option value="SX.PA">CS GROUP.</option>
                          <option value="ALCYB.PA">CYBERGUN</option>
                          <option value="CYBBT.PA">CYBERGUN BSA 2</option>
                          <option value="CYBK1.PA">CYBERGUN BSA K1</option>
                          <option value="CYBKA.PA">CYBERGUN BSA K2A</option>
                          <option value="CYBKB.PA">CYBERGUN BSA K2B</option>
                          <option value="ALDLS.PA">D.L.S.I.</option>
                          <option value="MLGEL.PA">D2L GROUP</option>
                          <option value="DLT.PA">DALET</option>
                          <option value="MLDAM.PA">DAMARIS</option>
                          <option value="ALDAR.PA">DAMARTEX</option>
                          <option value="BN.PA">DANONE</option>
                          <option value="AM.PA">DASSAULT AVIATION</option>
                          <option value="DSY.PA">DASSAULT SYSTEMES</option>
                          <option value="ALDBT.PA">DBT</option>
                          <option value="DBV.PA">DBV TECHNOLOGIES</option>
                          <option value="ALDEI.PA">DEINOVE</option>
                          <option value="ALDEL.PA">DELFINGEN</option>
                          <option value="ALDR.PA">DELTA DRONE</option>
                          <option value="ALDBS.PA">DELTA DRONE BSA</option>
                          <option value="ALDBY.PA">DELTA DRONE BSA Y</option>
                          <option value="DLTA.PA">DELTA PLUS GROUP</option>
                          <option value="DBG.PA">DERICHEBOURG</option>
                          <option value="MLDYH.PA">DESIGN YOUR HOME</option>
                          <option value="ALDEV.PA">DEVERNOIS</option>
                          <option value="DVT.PA">DEVOTEAM</option>
                          <option value="DGE.PA">DIAGEO</option>
                          <option value="DGM.PA">DIAGNOSTIC MEDICAL</option>
                          <option value="ALDNX.PA">DNXCORP</option>
                          <option value="DPAM.PA">DOCK.PETR.AMBES AM</option>
                          <option value="ALDOL.PA">DOLFINES</option>
                          <option value="ALDNE.PA">DONTNOD</option>
                          <option value="ALDRV.PA">DRONE VOLT</option>
                          <option value="DRODS.PA">DRONE VOLT DS</option>
                          <option value="MLDYN.PA">DYNAFOND</option>
                          <option value="MLDYX.PA">DYNEX ENERGY SA</option>
                          <option value="MLEAS.PA">EASSON HOLDINGS</option>
                          <option value="ALEZV.PA">EASYVISTA</option>
                          <option value="MLEDR.PA">EAUX DE ROYAN</option>
                          <option value="MLEAV.PA">EAVS</option>
                          <option value="ECASA.PA">ECA</option>
                          <option value="MLECO.PA">ECOLUTIONS</option>
                          <option value="ALECO.PA">ECOMIAM</option>
                          <option value="ALESA.PA">ECOSLOPS</option>
                          <option value="EDEN.PA">EDENRED</option>
                          <option value="EDF.PA">EDF</option>
                          <option value="ALEAC.PA">EDILIZIACROBATICA</option>
                          <option value="MLEDS.PA">EDITIONS DU SIGNE</option>
                          <option value="MLEDU.PA">EDUNIVERSAL</option>
                          <option value="MLEES.PA">EES</option>
                          <option value="GID.PA">EGIDE</option>
                          <option value="FGR.PA">EIFFAGE</option>
                          <option value="EKI.PA">EKINOPS</option>
                          <option value="ELEC.PA">ELEC.STRASBOURG</option>
                          <option value="EEM.PA">ELECT. MADAGASCAR</option>
                          <option value="ELIOR.PA">ELIOR GROUP</option>
                          <option value="ELIS.PA">ELIS</option>
                          <option value="ALEMV.PA">EMOVA GROUP</option>
                          <option value="ALDUB.PA">ENCRES DUBUIT</option>
                          <option value="ALNN6.PA">ENENSYS</option>
                          <option value="ALNRG.PA">ENERGISME</option>
                          <option value="ALENE.PA">ENERTIME</option>
                          <option value="ENGI.PA">ENGIE</option>
                          <option value="EPS.PA">ENGIE EPS</option>
                          <option value="ALENT.PA">ENTREPARTICULIERS</option>
                          <option value="ALENR.PA">ENTREPRENDRE</option>
                          <option value="ALTEV.PA">ENVEA</option>
                          <option value="ALEO2.PA">EO2</option>
                          <option value="EOSI.PA">EOS IMAGING</option>
                          <option value="ERA.PA">ERAMET</option>
                          <option value="ERYP.PA">ERYTECH PHARMA</option>
                          <option value="ESI.PA">ESI GROUP</option>
                          <option value="ALESK.PA">ESKER</option>
                          <option value="ESP.PA">ESPERITE</option>
                          <option value="EL.PA">ESSILORLUXOTTICA</option>
                          <option value="ES.PA">ESSO</option>
                          <option value="EFI.PA">EURASIA FONC INV</option>
                          <option value="ALEUA.PA">EURASIA GROUPE</option>
                          <option value="RF.PA">EURAZEO</option>
                          <option value="EUR.PA">EURO RESSOURCES</option>
                          <option value="ALERS.PA">EUROBIO-SCIENTIFIC</option>
                          <option value="ALECR.PA">EUROFINS CEREP</option>
                          <option value="ERF.PA">EUROFINS SCIENT.</option>
                          <option value="ALGEM.PA">EUROGERM</option>
                          <option value="MLERO.PA">EUROLAND CORPORATE</option>
                          <option value="ALEMG.PA">EUROMEDIS GROUPE</option>
                          <option value="ENX.PA">EURONEXT</option>
                          <option value="ECP.PA">EUROPACORP</option>
                          <option value="EUCAR.PA">EUROPCAR MOBILITY</option>
                          <option value="ALEUP.PA">EUROPLASMA</option>
                          <option value="EURBU.PA">EUROPLASMA BSC</option>
                          <option value="ETL.PA">EUTELSAT COMMUNIC.</option>
                          <option value="EGR.PA">EVERGREEN</option>
                          <option value="MLEVE.PA">EVERSET</option>
                          <option value="ALTVO.PA">EVOLIS</option>
                          <option value="EXAC.PA">EXACOMPTA CLAIREF.</option>
                          <option value="EXE.PA">EXEL INDUSTRIES</option>
                          <option value="EPCP.PA">EXPLOS.PROD.CHI.PF</option>
                          <option value="EXPL.PA">EXPLOSIFS PROD.CHI</option>
                          <option value="ALPHI.PA">FACEPHI</option>
                          <option value="ALFBA.PA">FASHION B AIR</option>
                          <option value="EO.PA">FAURECIA</option>
                          <option value="FAUV.PA">FAUVET GIREL</option>
                          <option value="FAYE.PA">FAYENC.SARREGUEMI.</option>
                          <option value="MLFDV.PA">FD</option>
                          <option value="FDJ.PA">FDJ</option>
                          <option value="FCMC.PA">FERM.CAS.MUN.CANNE</option>
                          <option value="FALG.PA">FERMENTALG</option>
                          <option value="FFP.PA">FFP</option>
                          <option value="SACI.PA">FIDUCIAL OFF.SOL.</option>
                          <option value="ORIA.PA">FIDUCIAL REAL EST.</option>
                          <option value="FGA.PA">FIGEAC AERO</option>
                          <option value="ALFIL.PA">FILAE</option>
                          <option value="BERR.PA">FIN.ETANG BERRE</option>
                          <option value="EBPF.PA">FIN.ETANG BERRE PF</option>
                          <option value="FOAF.PA">FIN.OUEST AFRICAIN</option>
                          <option value="FINM.PA">FINANCIERE MARJOS</option>
                          <option value="ODET.PA">FINANCIERE ODET</option>
                          <option value="FNTS.PA">FINATIS</option>
                          <option value="MLFXO.PA">FINAXO</option>
                          <option value="FIPP.PA">FIPP</option>
                          <option value="MLFIR.PA">FIRSTCAUTION</option>
                          <option value="ALFLE.PA">FLEURY MICHON</option>
                          <option value="FNAC.PA">FNAC DARTY</option>
                          <option value="ALFOC.PA">FOCUS HOME INT</option>
                          <option value="FPN.PA">FONC. PARIS NORD</option>
                          <option value="LEBL.PA">FONCIERE 7 INVEST</option>
                          <option value="FATL.PA">FONCIERE ATLAND</option>
                          <option value="EURS.PA">FONCIERE EURIS</option>
                          <option value="INEA.PA">FONCIERE INEA</option>
                          <option value="FLY.PA">FONCIERE LYONNAISE</option>
                          <option value="MLVIN.PA">FONCIERE VINDI</option>
                          <option value="SPEL.PA">FONCIERE VOLTA</option>
                          <option value="FORE.PA">FORESTIERE EQUAT.</option>
                          <option value="ALFPC.PA">FOUNTAINE PAJOT</option>
                          <option value="LFDE.PA">FRANCAISE ENERGIE</option>
                          <option value="MLFSG.PA">FRANCE SOIR GROUPE</option>
                          <option value="MLFTI.PA">FRANCE TOURISME</option>
                          <option value="ALFRE.PA">FREELANCE.COM</option>
                          <option value="FREY.PA">FREY</option>
                          <option value="MLGAI.PA">G.A.I.</option>
                          <option value="MLGAL.PA">GALEO</option>
                          <option value="GALIM.PA">GALIMMO</option>
                          <option value="ALBI.PA">GASCOGNE</option>
                          <option value="GAM.PA">GAUMONT</option>
                          <option value="ALGAU.PA">GAUSSIN</option>
                          <option value="GAUBS.PA">GAUSSIN BSAR</option>
                          <option value="GEA.PA">GEA GRENOBL.ELECT.</option>
                          <option value="GECP.PA">GECI INTL</option>
                          <option value="GECBT.PA">GECI INTL BSAR A</option>
                          <option value="GFC.PA">GECINA</option>
                          <option value="GNE.PA">GENERAL ELECTRIC</option>
                          <option value="GENX.PA">GENERIX GROUP</option>
                          <option value="GNRO.PA">GENEURO</option>
                          <option value="GNFT.PA">GENFIT</option>
                          <option value="GKTX.PA">GENKYOTEX</option>
                          <option value="GV.PA">GENOMIC VISION</option>
                          <option value="ALGEN.PA">GENOWAY</option>
                          <option value="SIGHT.PA">GENSIGHT BIOLOGICS</option>
                          <option value="MLGEQ.PA">GENTLEMENS EQUITY</option>
                          <option value="GEPBS.PA">GEP BSA 2020</option>
                          <option value="GET.PA">GETLINK SE</option>
                          <option value="ALGEV.PA">GEVELOT</option>
                          <option value="GLO.PA">GL EVENTS</option>
                          <option value="ALGBE.PA">GLOBAL BIOENERGIES</option>
                          <option value="ALGEP.PA">GLOBAL ECOPOWER</option>
                          <option value="ALGLD.PA">GOLD BY GOLD</option>
                          <option value="MLGML.PA">GOUR MEDICAL</option>
                          <option value="GPE.PA">GPE GROUP PIZZORNO</option>
                          <option value="ALPAR.PA">GPE PAROT (AUTO)</option>
                          <option value="GRVO.PA">GRAINES VOLTZ</option>
                          <option value="MLCMG.PA">GRECEMAR</option>
                          <option value="MLGRC.PA">GROUPE CARNIVOR</option>
                          <option value="CEN.PA">GROUPE CRIT</option>
                          <option value="FLO.PA">GROUPE FLO</option>
                          <option value="GOE.PA">GROUPE GORGE</option>
                          <option value="ALGIL.PA">GROUPE GUILLIN</option>
                          <option value="IRD.PA">GROUPE IRD</option>
                          <option value="GJAJ.PA">GROUPE JAJ</option>
                          <option value="ALLDL.PA">GROUPE LDLC</option>
                          <option value="OPN.PA">GROUPE OPEN</option>
                          <option value="PARP.PA">GROUPE PARTOUCHE</option>
                          <option value="MLPVG.PA">GROUPE PLUS-VALUES</option>
                          <option value="SFPI.PA">GROUPE SFPI</option>
                          <option value="ALGTR.PA">GROUPE TERA</option>
                          <option value="ALIMO.PA">GROUPIMO</option>
                          <option value="GTBP.PA">GT BIOPHARMA INC</option>
                          <option value="GTT.PA">GTT</option>
                          <option value="MLGDI.PA">GUANDAO PUER INVES</option>
                          <option value="GBT.PA">GUERBET</option>
                          <option value="GUI.PA">GUILLEMOT</option>
                          <option value="ALHEO.PA">H2O INNOVATION INC</option>
                          <option value="PIG.PA">HAULOTTE GROUP</option>
                          <option value="MLAHC.PA">HEALTH</option>
                          <option value="MLHAY.PA">HEALTHCARE ACTIVOS</option>
                          <option value="ALHRG.PA">HERIGE</option>
                          <option value="RMS.PA">HERMES INTL</option>
                          <option value="HEXA.PA">HEXAOM</option>
                          <option value="HF.PA">HF</option>
                          <option value="HCO.PA">HIGH CO</option>
                          <option value="ALHIO.PA">HIOLLE INDUSTRIES</option>
                          <option value="HIPAY.PA">HIPAY GROUP</option>
                          <option value="ALHIT.PA">HITECHPROS</option>
                          <option value="MLHK.PA">HK</option>
                          <option value="MLHBB.PA">HOCHE BAINS L.BAIN</option>
                          <option value="ALHGR.PA">HOFFMANN</option>
                          <option value="MLHCF.PA">HOME CONCEPT</option>
                          <option value="MLHPE.PA">HOPENING</option>
                          <option value="HOP.PA">HOPSCOTCH GROUPE</option>
                          <option value="ALHSW.PA">HORIZONTALSOFTWARE</option>
                          <option value="MLHMC.PA">HOT.MAJESTIC CANNE</option>
                          <option value="MLHOT.PA">HOTELIM</option>
                          <option value="HDP.PA">HOTELS DE PARIS</option>
                          <option value="MLHIN.PA">HOTL.IMMOB.NICE</option>
                          <option value="HSB.PA">HSBC HOLDINGS</option>
                          <option value="ALHYG.PA">HYBRIGENICS</option>
                          <option value="MLHYD.PA">HYDRAULIQUE PB</option>
                          <option value="MLHYE.PA">HYDRO-EXPLOIT.</option>
                          <option value="ALICR.PA">I.CERAM</option>
                          <option value="ALI2S.PA">I2S</option>
                          <option value="MLINT.PA">IANTE INVESTMENTS</option>
                          <option value="ICAD.PA">ICADE</option>
                          <option value="IDL.PA">ID LOGISTICS GROUP</option>
                          <option value="IDIP.PA">IDI</option>
                          <option value="MLIDS.PA">IDS</option>
                          <option value="ALIDS.PA">IDSUD</option>
                          <option value="IFF.PA">IFF</option>
                          <option value="IGE.PA">IGE + XAO</option>
                          <option value="ILD.PA">ILIAD</option>
                          <option value="MLIML.PA">IMALLIANCE</option>
                          <option value="NK.PA">IMERYS</option>
                          <option value="MLIPP.PA">IMM.PARIS.PERLE</option>
                          <option value="ALIMR.PA">IMMERSION</option>
                          <option value="IMDA.PA">IMMOB.DASSAULT</option>
                          <option value="ALIMP.PA">IMPLANET</option>
                          <option value="MLIMP.PA">IMPRIMERIE CHIRAT</option>
                          <option value="INFE.PA">INDLE FIN.ENTREPR.</option>
                          <option value="MLIFC.PA">INFOCLIP</option>
                          <option value="INF.PA">INFOTEL</option>
                          <option value="MLISP.PA">INMOSUPA</option>
                          <option value="IPH.PA">INNATE PHARMA</option>
                          <option value="INN.PA">INNELEC MULTIMEDIA</option>
                          <option value="MLIDP.PA">INNOVADERMA PLC</option>
                          <option value="MLIRF.PA">INNOVATIVE RFK SPA</option>
                          <option value="ALLUX.PA">INSTALLUX</option>
                          <option value="ALINT.PA">INTEGRAGEN</option>
                          <option value="ITP.PA">INTERPARFUMS</option>
                          <option value="ITXT.PA">INTEXA</option>
                          <option value="ALINS.PA">INTRASENSE</option>
                          <option value="IVA.PA">INVENTIVA</option>
                          <option value="ALINV.PA">INVIBES ADVERTSING</option>
                          <option value="MLIOC.PA">IOC HOLDING</option>
                          <option value="MLIPO.PA">IPOSA PROPERTIES</option>
                          <option value="IPN.PA">IPSEN</option>
                          <option value="IPS.PA">IPSOS</option>
                          <option value="ALITL.PA">IT LINK</option>
                          <option value="MLITN.PA">ITALY INNOVAZIONI</option>
                          <option value="ITE.PA">ITESOFT</option>
                          <option value="ALIVA.PA">IVALIS</option>
                          <option value="JBOG.PA">JACQUES BOGART</option>
                          <option value="JCQ.PA">JACQUET METALS</option>
                          <option value="DEC.PA">JC DECAUX SA.</option>
                          <option value="MLJSA.PA">JSA TECHNOLOGY</option>
                          <option value="ALKAL.PA">KALRAY</option>
                          <option value="KOF.PA">KAUFMAN ET BROAD</option>
                          <option value="KER.PA">KERING</option>
                          <option value="ALKLK.PA">KERLINK</option>
                          <option value="KEY.PA">KEYRUS</option>
                          <option value="ALKKO.PA">KKO INTERNATIONAL</option>
                          <option value="LI.PA">KLEPIERRE</option>
                          <option value="ALSIM.PA">KLIMVEST</option>
                          <option value="KORI.PA">KORIAN</option>
                          <option value="MLKRI.PA">KRIEF GROUP</option>
                          <option value="MLVAP.PA">KUMULUS VAPE</option>
                          <option value="OR.PA">L''OREAL</option>
                          <option value="LFVE.PA">LA FONCIERE VERTE</option>
                          <option value="ALPER.PA">LA PERLA FASHION</option>
                          <option value="LACR.PA">LACROIX SA</option>
                          <option value="LHN.PA">LAFARGEHOLCIM LTD</option>
                          <option value="LAF.PA">LAFUMA</option>
                          <option value="MMB.PA">LAGARDERE S.C.A.</option>
                          <option value="ALLAN.PA">LANSON-BCC</option>
                          <option value="LAT.PA">LATECOERE</option>
                          <option value="LPE.PA">LAURENT-PERRIER</option>
                          <option value="LOUP.PA">LDC</option>
                          <option value="ALTAN.PA">LE TANNEUR</option>
                          <option value="LBON.PA">LEBON</option>
                          <option value="LSS.PA">LECTRA</option>
                          <option value="LR.PA">LEGRAND</option>
                          <option value="ALLHB.PA">LES HOTELS BAVEREZ</option>
                          <option value="TBMBT.PA">LESTQBLANC202212BS</option>
                          <option value="ALLEX.PA">LEXIBOOK LINGUIST.</option>
                          <option value="LIN.PA">LINEDATA SERVICES</option>
                          <option value="FII.PA">LISI</option>
                          <option value="ALLLN.PA">LLEIDA</option>
                          <option value="LNA.PA">LNA SANTE</option>
                          <option value="MLLOI.PA">LOCASYSTEM INTL</option>
                          <option value="ALLOG.PA">LOGIC INSTRUMENT</option>
                          <option value="MLLOG.PA">LOGIS CONFORT</option>
                          <option value="MLCAC.PA">LOMBARD ET MEDOT</option>
                          <option value="ALUCI.PA">LUCIBEL</option>
                          <option value="LUCBS.PA">LUCIBEL BS</option>
                          <option value="LBIRD.PA">LUMIBIRD</option>
                          <option value="MLV4S.PA">LV4S</option>
                          <option value="MC.PA">LVMH</option>
                          <option value="LYS.PA">LYSOGENE</option>
                          <option value="MRM.PA">M.R.M</option>
                          <option value="ALMII.PA">M2I</option>
                          <option value="MLMAD.PA">MADE</option>
                          <option value="ALMNG.PA">MADVERTISE</option>
                          <option value="MLMGL.PA">MAGILLEM</option>
                          <option value="MLMAB.PA">MAIS.ANTOINE BAUD</option>
                          <option value="MLCLI.PA">MAISON CLIO BLUE</option>
                          <option value="MLMAI.PA">MAISONS D'AUJOURD</option>
                          <option value="MDM.PA">MAISONS DU MONDE</option>
                          <option value="ALMAK.PA">MAKHEIA GROUP</option>
                          <option value="MAKBS.PA">MAKHEIA GROUP BSA</option>
                          <option value="ALMKS.PA">MAKING SCIENCE</option>
                          <option value="MALT.PA">MALTERIES FCO-BEL.</option>
                          <option value="MTU.PA">MANITOU BF</option>
                          <option value="MAN.PA">MANUTAN INTL</option>
                          <option value="MLMAQ.PA">MAQ ADMON. URBANAS</option>
                          <option value="ALMAR.PA">MARE NOSTRUM</option>
                          <option value="IAM.PA">MAROC TELECOM</option>
                          <option value="ALMAS.PA">MASTRAD</option>
                          <option value="MASBS.PA">MASTRAD BS29</option>
                          <option value="MKEA.PA">MAUNA KEA TECH</option>
                          <option value="MAU.PA">MAUREL ET PROM</option>
                          <option value="MBWS.PA">MBWS</option>
                          <option value="MBWBT.PA">MBWS BSA 2022</option>
                          <option value="MBWSZ.PA">MBWS BSAR 2023</option>
                          <option value="MCPHY.PA">MCPHY ENERGY</option>
                          <option value="ALMEC.PA">MECELEC COMPOSITES</option>
                          <option value="EDI.PA">MEDIA 6</option>
                          <option value="MLLAB.PA">MEDIA LAB</option>
                          <option value="ALKER.PA">MEDIA MAKER</option>
                          <option value="ALMDT.PA">MEDIANTECHNOLOGIES</option>
                          <option value="MDW.PA">MEDIAWAN</option>
                          <option value="MDWBS.PA">MEDIAWAN WAR</option>
                          <option value="MEDCL.PA">MEDINCELL</option>
                          <option value="MLMCE.PA">MEDIOCREDITO EUROP</option>
                          <option value="MEMS.PA">MEMSCAP REGPT</option>
                          <option value="MERY.PA">MERCIALYS</option>
                          <option value="MRK.PA">MERCK AND CO INC</option>
                          <option value="MRN.PA">MERSEN</option>
                          <option value="METBS.PA">METABOLIC EX BSA21</option>
                          <option value="METEX.PA">METABOLIC EXPLORER</option>
                          <option value="MLETA.PA">METALLIANCE</option>
                          <option value="ALMET.PA">METHANOR</option>
                          <option value="ALMTH.PA">METHORIOS CAPITAL</option>
                          <option value="MLMIB.PA">METRICS IN BALANCE</option>
                          <option value="MMT.PA">METROPOLE TV</option>
                          <option value="ALMGI.PA">MG INTERNATIONAL</option>
                          <option value="ALMDG.PA">MGI DIGITAL GRAPHI</option>
                          <option value="ML.PA">MICHELIN</option>
                          <option value="MUN.PA">MICROPOLE</option>
                          <option value="MLSKN.PA">MICROSKIN</option>
                          <option value="ALMIC.PA">MICROWAVE VISION</option>
                          <option value="MLNMA.PA">MIGUET ET ASSOCIES</option>
                          <option value="ALMLB.PA">MILIBOO</option>
                          <option value="ALBUD.PA">MINT</option>
                          <option value="BUDBS.PA">MINT BS</option>
                          <option value="MLAMY.PA">MLD</option>
                          <option value="ALMND.PA">MND</option>
                          <option value="ALMBS.PA">MND BSA 2019</option>
                          <option value="MONC.PA">MONCEY (FIN.) NOM.</option>
                          <option value="MLMON.PA">MONFINANCIER</option>
                          <option value="MONT.PA">MONTEA C.V.A.</option>
                          <option value="ALMOU.PA">MOULINVEST</option>
                          <option value="ALMRB.PA">MR BRICOLAGE</option>
                          <option value="MLMRE.PA">MRE-III.P-5.SOCIMI</option>
                          <option value="MLMTD.PA">MTD FINANCE</option>
                          <option value="MLMUL.PA">MULANN</option>
                          <option value="MLMMC.PA">MULTIMICROCLOUD</option>
                          <option value="ALMUN.PA">MUNIC</option>
                          <option value="GREV.PA">MUSEE GREVIN</option>
                          <option value="ALMBG.PA">MYBEST GROUP</option>
                          <option value="NACON.PA">NACON</option>
                          <option value="NANO.PA">NANOBIOTIX</option>
                          <option value="KN.PA">NATIXIS</option>
                          <option value="MLNAT.PA">NATURE ET LOGIS</option>
                          <option value="NAVYA.PA">NAVYA</option>
                          <option value="MLNEO.PA">NEOCOM MULTIMEDIA</option>
                          <option value="NEOEN.PA">NEOEN</option>
                          <option value="ALNLF.PA">NEOLIFE</option>
                          <option value="NLFBS.PA">NEOLIFE BS</option>
                          <option value="ALNEV.PA">NEOVACS</option>
                          <option value="NEVBS.PA">NEOVACS BSA</option>
                          <option value="NTG.PA">NETGEM</option>
                          <option value="NRO.PA">NEURONES</option>
                          <option value="MLNEI.PA">NEWSINVEST</option>
                          <option value="NEX.PA">NEXANS</option>
                          <option value="NXI.PA">NEXITY</option>
                          <option value="ALNXT.PA">NEXTEDIA</option>
                          <option value="NEXTS.PA">NEXTSTAGE</option>
                          <option value="COX.PA">NICOX</option>
                          <option value="NOKIA.PA">NOKIA</option>
                          <option value="ALNOV.PA">NOVACYT</option>
                          <option value="MLNOV.PA">NOVATECH IND.</option>
                          <option value="ALNOX.PA">NOXXON</option>
                          <option value="NR21.PA">NR21</option>
                          <option value="NRG.PA">NRJ GROUP</option>
                          <option value="ALNSC.PA">NSC GROUPE</option>
                          <option value="ALNSE.PA">NSE</option>
                          <option value="MLOSA.PA">O SORBET D AMOUR</option>
                          <option value="ALODI.PA">O2I</option>
                          <option value="O2IBS.PA">O2I BSA</option>
                          <option value="ODBS2.PA">O2I BSA 2</option>
                          <option value="ALOBR.PA">OBER</option>
                          <option value="MLOCT.PA">OCTOPUS ROBOTS</option>
                          <option value="SBT.PA">OENEO</option>
                          <option value="OLG.PA">OL GROUPE</option>
                          <option value="MLOLM.PA">OLMIX</option>
                          <option value="ALONC.PA">ONCODESIGN</option>
                          <option value="MLOEX.PA">ONE EXPERIENCE</option>
                          <option value="MLONL.PA">ONLINEFORMAPRO</option>
                          <option value="ONXEO.PA">ONXEO</option>
                          <option value="ORA.PA">ORANGE</option>
                          <option value="ORAP.PA">ORAPI</option>
                          <option value="ORAPB.PA">ORAPI BSA</option>
                          <option value="MLORB.PA">ORBIS PROPERTIES</option>
                          <option value="KAZI.PA">ORCHESTRA-PREMAMAN</option>
                          <option value="ALORD.PA">ORDISSIMO</option>
                          <option value="OREGE.PA">OREGE</option>
                          <option value="ORP.PA">ORPEA</option>
                          <option value="OSE.PA">OSE IMMUNO</option>
                          <option value="ALOSM.PA">OSMOZIS</option>
                          <option value="MLPAC.PA">PACTE NOVATION</option>
                          <option value="PID.PA">PARAGON ID</option>
                          <option value="PAR.PA">PAREF</option>
                          <option value="MLPFX.PA">PARFEX</option>
                          <option value="PARRO.PA">PARROT</option>
                          <option value="PABSA.PA">PARROT BSA 1</option>
                          <option value="PABSB.PA">PARROT BSA 2</option>
                          <option value="MLHOP.PA">PART.INDLES MINI.</option>
                          <option value="MLPRX.PA">PARX MATERIALS NV</option>
                          <option value="PSAT.PA">PASSAT</option>
                          <option value="PAT.PA">PATRIMOINE ET COMM</option>
                          <option value="ALPAU.PA">PAULIC MEUNERIE</option>
                          <option value="PCA.PA">PCAS</option>
                          <option value="RI.PA">PERNOD RICARD</option>
                          <option value="PERR.PA">PERRIER (GERARD)</option>
                          <option value="UG.PA">PEUGEOT</option>
                          <option value="PHA.PA">PHARMAGEST INTER.</option>
                          <option value="ALPHS.PA">PHARMASIMPLE</option>
                          <option value="ALPHA.PA">PHARNEXT</option>
                          <option value="MLPHW.PA">PHONE WEB</option>
                          <option value="MLPHO.PA">PHOTONIKE CAPITAL</option>
                          <option value="VAC.PA">PIERRE VACANCES</option>
                          <option value="ALPDX.PA">PISCINES DESJOYAUX</option>
                          <option value="ALPIX.PA">PIXIUM VISION</option>
                          <option value="MLPLC.PA">PLACOPLATRE</option>
                          <option value="ALPLA.PA">PLANET MEDIA</option>
                          <option value="ALPAT.PA">PLANT ADVANCED</option>
                          <option value="PATBS.PA">PLANT ADVANCED BS</option>
                          <option value="PVL.PA">PLAST.VAL LOIRE</option>
                          <option value="POM.PA">PLASTIC OMNIUM</option>
                          <option value="ALPJT.PA">POUJOULAT</option>
                          <option value="ALPOU.PA">POULAILLON</option>
                          <option value="POXEL.PA">POXEL</option>
                          <option value="PREC.PA">PRECIA</option>
                          <option value="ALPRE.PA">PREDILIFE</option>
                          <option value="ALPRI.PA">PRISMAFLEX INTL</option>
                          <option value="PROAC.PA">PROACTIS SA</option>
                          <option value="ALPRO.PA">PRODWARE</option>
                          <option value="PWG.PA">PRODWAYS</option>
                          <option value="PRBS1.PA">PROLOG BSAAR20</option>
                          <option value="PROL.PA">PROLOGUE</option>
                          <option value="PROBT.PA">PROLOGUE BSA</option>
                          <option value="PRBS2.PA">PROLOGUE BSAA2021</option>
                          <option value="MLPRI.PA">PROP.IMMEUBLES</option>
                          <option value="MLPRO.PA">PROVENTURE GOLD</option>
                          <option value="PSB.PA">PSB INDUSTRIES</option>
                          <option value="PUBBS.PA">PUBLICIS BSA</option>
                          <option value="PUB.PA">PUBLICIS GROUPE SA</option>
                          <option value="QDT.PA">QUADIENT</option>
                          <option value="ALQP.PA">QUADPACK</option>
                          <option value="ALQGC.PA">QUANTUM GENOMICS</option>
                          <option value="ALQWA.PA">QWAMPLIFY</option>
                          <option value="QWABS.PA">QWAMPLIFY BSAANE</option>
                          <option value="RAL.PA">RALLYE</option>
                          <option value="GDS.PA">RAMSAY GEN SANTE</option>
                          <option value="ML350.PA">RAPIDO PRET</option>
                          <option value="ALREA.PA">REALITES</option>
                          <option value="RX.PA">RECYLEX S.A.</option>
                          <option value="RCO.PA">REMY COINTREAU</option>
                          <option value="RNO.PA">RENAULT</option>
                          <option value="MLREX.PA">REVIVAL EXPANSION</option>
                          <option value="ALREW.PA">REWORLD MEDIA</option>
                          <option value="RXL.PA">REXEL</option>
                          <option value="ALRIB.PA">RIBER</option>
                          <option value="RBT.PA">ROBERTET</option>
                          <option value="CBR.PA">ROBERTET CDV 87</option>
                          <option value="CBE.PA">ROBERTET CI</option>
                          <option value="RBO.PA">ROCHE BOBOIS</option>
                          <option value="ALROC.PA">ROCTOOL</option>
                          <option value="ROCBS.PA">ROCTOOL BSA 2020</option>
                          <option value="ROCBT.PA">ROCTOOL BSA 2020-2</option>
                          <option value="ROTH.PA">ROTHSCHILD & CO</option>
                          <option value="ALRGR.PA">ROUGIER S.A.</option>
                          <option value="MLROU.PA">ROUSSELET CENTRIF.</option>
                          <option value="RUI.PA">RUBIS</option>
                          <option value="SK.PA">S.E.B.</option>
                          <option value="ALSAF.PA">SAFE ORTHOPAEDICS</option>
                          <option value="SAF.PA">SAFRAN</option>
                          <option value="ALWOO.PA">SAFWOOD</option>
                          <option value="SGO.PA">SAINT GOBAIN</option>
                          <option value="SABE.PA">SAINT JEAN GROUPE</option>
                          <option value="SAMS.PA">SAMSE</option>
                          <option value="SAN.PA">SANOFI</option>
                          <option value="ALMER.PA">SAPMER</option>
                          <option value="DIM.PA">SARTORIUS STED BIO</option>
                          <option value="SAVE.PA">SAVENCIA</option>
                          <option value="MLSDN.PA">SAVONNERIE NYONS</option>
                          <option value="MLSBT.PA">SBT</option>
                          <option value="MLSHD.PA">SCANDINAVIAN HOUSE</option>
                          <option value="CBSM.PA">SCBSM</option>
                          <option value="MLCMI.PA">SCEMI</option>
                          <option value="SLB.PA">SCHLUMBERGER</option>
                          <option value="SU.PA">SCHNEIDER ELECTRIC</option>
                          <option value="MLSCH.PA">SCHOBRUNN PARIS</option>
                          <option value="SCR.PA">SCOR SE</option>
                          <option value="SCHP.PA">SECHE ENVIRONNEM.</option>
                          <option value="SGRO.PA">SEGRO PLC</option>
                          <option value="ALSEI.PA">SEIF SPA</option>
                          <option value="SLCO.PA">SELCODIS</option>
                          <option value="SELER.PA">SELECTIRENTE</option>
                          <option value="MLSMP.PA">SEMPLICEMENTE SpA</option>
                          <option value="ALSEN.PA">SENSORION</option>
                          <option value="MLSEQ.PA">SEQUA PETROLEUM NV</option>
                          <option value="SEFER.PA">SERGEFERRARI GROUP</option>
                          <option value="ALSER.PA">SERMA GROUP</option>
                          <option value="SESG.PA">SES</option>
                          <option value="SESL.PA">SES IMAGOTAG</option>
                          <option value="SRP.PA">SHOWROOMPRIVE</option>
                          <option value="ALSIP.PA">SI PARTICIPATIONS</option>
                          <option value="ALBFR.PA">SIDETRADE</option>
                          <option value="GIRO.PA">SIGNAUX GIROD</option>
                          <option value="SII.PA">SII</option>
                          <option value="MLSIL.PA">SILC</option>
                          <option value="MLMAT.PA">SIMAT</option>
                          <option value="MLSIM.PA">SIMO INTERNATIONAL</option>
                          <option value="MLSNT.PA">SINTESI SpA</option>
                          <option value="MLSML.PA">SMALTO</option>
                          <option value="SMLBS.PA">SMALTO BSA</option>
                          <option value="SMCP.PA">SMCP</option>
                          <option value="SMTPC.PA">SMTPC</option>
                          <option value="SFCA.PA">SOC FRANC CASINOS</option>
                          <option value="GLE.PA">SOCIETE GENERALE</option>
                          <option value="SW.PA">SODEXO</option>
                          <option value="SEC.PA">SODITECH</option>
                          <option value="SFBS.PA">SOFIBUS PATRIMOINE</option>
                          <option value="SOFR.PA">SOFRAGI</option>
                          <option value="SOG.PA">SOGECLAIR</option>
                          <option value="SOI.PA">SOITEC</option>
                          <option value="LOCAL.PA">SOLOCAL GROUP</option>
                          <option value="S30.PA">SOLUTIONS 30 SE</option>
                          <option value="SOLB.PA">SOLVAY</option>
                          <option value="SO.PA">SOMFY SA</option>
                          <option value="SOP.PA">SOPRA STERIA GROUP</option>
                          <option value="MLSRP.PA">SPEED RABBIT PIZZA</option>
                          <option value="SPIE.PA">SPIE</option>
                          <option value="ALSGD.PA">SPINEGUARD</option>
                          <option value="ALSPW.PA">SPINEWAY</option>
                          <option value="SPI.PA">SPIR COMMUNICATION</option>
                          <option value="SQI.PA">SQLI</option>
                          <option value="DPT.PA">ST DUPONT</option>
                          <option value="MLSTM.PA">STEAM FRANCE</option>
                          <option value="STF.PA">STEF</option>
                          <option value="STNT.PA">STENTYS</option>
                          <option value="STM.PA">STMICROELECTRONICS</option>
                          <option value="ALSAS.PA">STRADIM ESPAC.FIN</option>
                          <option value="ALSTW.PA">STREAMWIDE</option>
                          <option value="STWDS.PA">STREAMWIDE BS</option>
                          <option value="MLSTR.PA">STREIT MECANIQUE</option>
                          <option value="SEV.PA">SUEZ</option>
                          <option value="MLSUM.PA">SUMO RESOURCES PLC</option>
                          <option value="SSI.PA">SUPERSONIC IMAGINE</option>
                          <option value="SWP.PA">SWORD GROUP</option>
                          <option value="SDG.PA">SYNERGIE</option>
                          <option value="TKTT.PA">TARKETT</option>
                          <option value="TAYN.PA">TAYNINH</option>
                          <option value="MLTEA.PA">TEAM</option>
                          <option value="TECBS.PA">TECH BSA 2024</option>
                          <option value="TCH.PA">TECHNICOLOR</option>
                          <option value="FTI.PA">TECHNIPFMC</option>
                          <option value="TEP.PA">TELEPERFORMANCE</option>
                          <option value="TVRB.PA">TELEVERBIER</option>
                          <option value="MLVST.PA">TELEVISTA</option>
                          <option value="TES.PA">TESSI</option>
                          <option value="TFI.PA">TF1</option>
                          <option value="TFF.PA">TFF GROUP</option>
                          <option value="HO.PA">THALES</option>
                          <option value="ALTBG.PA">THE BLOCKCHAIN GP</option>
                          <option value="ALTHE.PA">THERACLION</option>
                          <option value="ALTER.PA">THERADIAG</option>
                          <option value="ALTHX.PA">THERANEXUS</option>
                          <option value="THEP.PA">THERMADOR GROUPE</option>
                          <option value="TKO.PA">TIKEHAU CAPITAL</option>
                          <option value="TIPI.PA">TIPIAK</option>
                          <option value="TITC.PA">TITAN CEMENT</option>
                          <option value="TVLY.PA">TIVOLY</option>
                          <option value="ALTLX.PA">TOOLUX SANDING</option>
                          <option value="MLTBM.PA">TOQUEBLANCHEMONDE</option>
                          <option value="FP.PA">TOTAL</option>
                          <option value="EC.PA">TOTAL GABON</option>
                          <option value="TOUP.PA">TOUAX</option>
                          <option value="EIFF.PA">TOUR EIFFEL</option>
                          <option value="MLABO.PA">TOUTABO</option>
                          <option value="MLPSH.PA">TPSH</option>
                          <option value="MLTRA.PA">TRAMWAYS DE ROUEN</option>
                          <option value="TNG.PA">TRANSGENE</option>
                          <option value="TRI.PA">TRIGANO</option>
                          <option value="ALTRI.PA">TRILOGIQ</option>
                          <option value="MLTRO.PA">TROC ILE</option>
                          <option value="MLTRC.PA">TROIS CHENES</option>
                          <option value="ALTRO.PA">TRONICS</option>
                          <option value="ALTTI.PA">TTI</option>
                          <option value="ALTXC.PA">TXCOM</option>
                          <option value="ALU10.PA">U10 CORP</option>
                          <option value="UBI.PA">UBISOFT ENTERTAIN</option>
                          <option value="ALUCR.PA">UCAR</option>
                          <option value="MLUMG.PA">UMALIS GROUP</option>
                          <option value="ALUMS.PA">UMANIS</option>
                          <option value="MLUMH.PA">UNI.METALG.HT-SEI.</option>
                          <option value="URW.PA">UNIBAIL-RODAMCO-WE</option>
                          <option value="UNBL.PA">UNIBEL</option>
                          <option value="UFF.PA">UNION FIN.FRANCE</option>
                          <option value="FPG.PA">UNION TECH.INFOR.</option>
                          <option value="ALUNT.PA">UNITI</option>
                          <option value="ALUPG.PA">UPERGY</option>
                          <option value="ALUVI.PA">UV GERMI</option>
                          <option value="ALVAL.PA">VALBIOTIS</option>
                          <option value="FR.PA">VALEO</option>
                          <option value="VK.PA">VALLOUREC</option>
                          <option value="VLA.PA">VALNEVA</option>
                          <option value="MLVAL.PA">VALONEO</option>
                          <option value="ALVU.PA">VENTE UNIQUE.COM</option>
                          <option value="VIE.PA">VEOLIA ENVIRON.</option>
                          <option value="VRLA.PA">VERALLIA</option>
                          <option value="ALVER.PA">VERGNET</option>
                          <option value="VMX.PA">VERIMATRIX</option>
                          <option value="VRNL.PA">VERNEUIL FINANCE</option>
                          <option value="MLVER.PA">VERNEY CARRON</option>
                          <option value="VETO.PA">VETOQUINOL</option>
                          <option value="ALVIA.PA">VIALIFE</option>
                          <option value="VCT.PA">VICAT</option>
                          <option value="VDLO.PA">VIDELIO</option>
                          <option value="VIL.PA">VIEL ET COMPAGNIE</option>
                          <option value="RIN.PA">VILMORIN & CIE</option>
                          <option value="DG.PA">VINCI</option>
                          <option value="VIRP.PA">VIRBAC</option>
                          <option value="ALVIV.PA">VISIATIV</option>
                          <option value="MLVIS.PA">VISIO NERF</option>
                          <option value="SDT.PA">VISIODENT</option>
                          <option value="VMGBW.PA">VISIOMED BSA18T2.3</option>
                          <option value="VMGBX.PA">VISIOMED BSA18T2.4</option>
                          <option value="VMGBS.PA">VISIOMED BSA2018-1</option>
                          <option value="VMGBU.PA">VISIOMED BSA2018-2</option>
                          <option value="VMGBV.PA">VISIOMED BSA2018-3</option>
                          <option value="ALVMG.PA">VISIOMED GROUP</option>
                          <option value="VMGBT.PA">VISIOMEDBSA26OCT23</option>
                          <option value="VIV.PA">VIVENDI</option>
                          <option value="ALVGO.PA">VOGO</option>
                          <option value="VLTSA.PA">VOLTALIA</option>
                          <option value="VTX.PA">VOLUNTIS</option>
                          <option value="ALVDM.PA">VOYAGEURS DU MONDE</option>
                          <option value="VRAP.PA">VRANKEN-POMMERY</option>
                          <option value="MLVRF.PA">VREF SEVILLE</option>
                          <option value="ALLIX.PA">WALLIX</option>
                          <option value="WAVE.PA">WAVESTONE</option>
                          <option value="ALWEC.PA">WE.CONNECT</option>
                          <option value="MLWEA.PA">WEACCESS GROUP</option>
                          <option value="ALWED.PA">WEDIA</option>
                          <option value="MF.PA">WENDEL</option>
                          <option value="MLWEY.PA">WEYA</option>
                          <option value="MLWRC.PA">WHITENI R CAJAL</option>
                          <option value="ALWIT.PA">WITBE</option>
                          <option value="WLN.PA">WORLDLINE</option>
                          <option value="XFAB.PA">X-FAB</option>
                          <option value="XIL.PA">XILAM ANIMATION</option>
                          <option value="XPO.PA">XPO LOGISTICS</option>
                          <option value="MAGIS.PA">YMAGIS</option>
                          <option value="MAGBS.PA">YMAGIS BSA</option>
                          <option value="MLZAM.PA">ZCCM</option>
                          <option value="CV.PA">ZCI LIMITED</option>



                        </select>
                      </div>

                      <p>
                        <Text id="integration.stockExchange.instructionsToUse" />
                      </p>
                      <div class="form-group">
                        <span class="input-group-append">
                          <button class="btn btn-primary" onClick={props.saveConfiguration}>
                            <Text id={`integration.stockExchange.saveButton`} />
                          </button>
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
);

export default StockExchangePage;
