const { expect } = require('chai');
const sinon = require('sinon');

const Zigbee2MqttService = require('../../../../services/zigbee2mqtt');

const discoveredDevices = require('./payloads/mqtt_devices_get.json');
const expectedDevicesPayload = require('./payloads/event_device_result.json');

const aqaraWithDuplicateFeatureDevice = require('./payloads/aqara_with_duplicate_feature_mqtt.json');

const {
  DEVICE_FEATURE_CATEGORIES,
  DEVICE_FEATURE_TYPES,
  DEVICE_FEATURE_UNITS,
} = require('../../../../utils/constants');

const gladys = {
  job: {
    wrapper: (type, func) => {
      return async () => {
        return func();
      };
    },
  },
  stateManager: {
    get: {},
  },
};
const serviceId = 'f87b7af2-ca8e-44fc-b754-444354b42fee';

describe('zigbee2mqtt getDiscoveredDevices', () => {
  // PREPARE
  const zigbee2MqttService = Zigbee2MqttService(gladys, serviceId);

  beforeEach(() => {
    gladys.stateManager.get = sinon.stub();
  });

  it('get no discovered devices', async () => {
    // EXECUTE
    const devices = zigbee2MqttService.device.getDiscoveredDevices();
    // ASSERT
    expect(devices).deep.eq([]);
  });

  it('get discovered devices', async () => {
    // PREPARE
    gladys.stateManager.get
      .onFirstCall()
      .returns({ id: 'gladys-id', room_id: 'room_id', name: 'device-name' })
      .onSecondCall()
      .returns(expectedDevicesPayload[1])
      .onThirdCall()
      .returns(false);

    discoveredDevices
      .filter((d) => d.supported)
      .forEach((device) => {
        zigbee2MqttService.device.discoveredDevices[device.friendly_name] = device;
      });

    // EXECUTE
    const devices = zigbee2MqttService.device.getDiscoveredDevices();
    // ASSERT
    expect(devices).deep.eq(expectedDevicesPayload);
  });

  it('get discovered devices without duplicate features', async () => {
    // PREPARE
    gladys.stateManager.get
      .onFirstCall()
      .returns({ id: 'gladys-id', room_id: 'room_id', name: 'device-name' })
      .onSecondCall()
      .returns(expectedDevicesPayload[3])
      .onThirdCall()
      .returns(false);

    aqaraWithDuplicateFeatureDevice
      .filter((d) => d.supported)
      .forEach((device) => {
        zigbee2MqttService.device.discoveredDevices[device.friendly_name] = device;
      });

    // EXECUTE
    const devices = zigbee2MqttService.device.getDiscoveredDevices();
    const aqaraDevice = devices.find((d) => d.model === 'WSDCGQ11LM');
    // ASSERT
    expect(aqaraDevice.features.filter((f) => f.category === 'humidity-sensor')).to.have.lengthOf(
      1,
      'should not have duplicate humidity',
    );
  });

  it('filter discovered devices', async () => {
    // PREPARE
    gladys.stateManager.get
      .onFirstCall()
      .returns({ id: 'gladys-id', room_id: 'room_id', name: 'device-name' })
      .onSecondCall()
      .returns(expectedDevicesPayload[1])
      .onThirdCall()
      .returns(false);

    discoveredDevices
      .filter((d) => d.supported)
      .forEach((device) => {
        zigbee2MqttService.device.discoveredDevices[device.friendly_name] = device;
      });

    // EXECUTE
    const devices = zigbee2MqttService.device.getDiscoveredDevices({ filter_existing: true });
    // ASSERT
    // Expected devices but first
    const filteredExpectedDevices = [...expectedDevicesPayload];
    filteredExpectedDevices.splice(1, 1);
    expect(devices).deep.eq(filteredExpectedDevices);
  });

  it('should not mark device as updatable when only energy consumption/cost features differ', async () => {
    // PREPARE
    // Simulate a device with energy features in the existing device (from DB)
    // but not in the new device from Zigbee2mqtt
    // The consumption/cost features are generated by Gladys, not Zigbee2mqtt
    const existingDeviceWithEnergyFeatures = {
      id: 'existing-device-id',
      external_id: 'zigbee2mqtt:my_device',
      room_id: 'room_id',
      name: 'Existing Device',
      features: [
        {
          id: 'feature-1',
          external_id: 'zigbee2mqtt:my_device:switch:energy:energy',
          category: DEVICE_FEATURE_CATEGORIES.SWITCH,
          type: DEVICE_FEATURE_TYPES.SWITCH.ENERGY,
          unit: DEVICE_FEATURE_UNITS.KILOWATT_HOUR,
        },
        {
          id: 'consumption-feature-id',
          external_id: 'zigbee2mqtt:my_device:switch:energy:energy_consumption',
          category: DEVICE_FEATURE_CATEGORIES.ENERGY_SENSOR,
          type: DEVICE_FEATURE_TYPES.ENERGY_SENSOR.THIRTY_MINUTES_CONSUMPTION,
          energy_parent_id: 'feature-1',
        },
        {
          id: 'cost-feature-id',
          external_id: 'zigbee2mqtt:my_device:switch:energy:energy_cost',
          category: DEVICE_FEATURE_CATEGORIES.ENERGY_SENSOR,
          type: DEVICE_FEATURE_TYPES.ENERGY_SENSOR.THIRTY_MINUTES_CONSUMPTION_COST,
          energy_parent_id: 'consumption-feature-id',
        },
      ],
    };

    gladys.stateManager.get.returns(existingDeviceWithEnergyFeatures);

    // Zigbee2mqtt device only has the energy feature (no consumption/cost - those are generated by Gladys)
    zigbee2MqttService.device.discoveredDevices = {
      my_device: {
        friendly_name: 'my_device',
        supported: true,
        definition: {
          model: 'Test Model',
          exposes: [{ type: 'numeric', name: 'energy', property: 'energy', unit: 'kWh', access: 1 }],
        },
      },
    };

    // EXECUTE
    const devices = zigbee2MqttService.device.getDiscoveredDevices();

    // ASSERT
    expect(devices).to.have.lengthOf(1);
    expect(devices[0].updatable).to.equal(false);
    // Verify that consumption and cost features are present and preserved
    const consumptionFeature = devices[0].features.find(
      (f) => f.type === DEVICE_FEATURE_TYPES.ENERGY_SENSOR.THIRTY_MINUTES_CONSUMPTION,
    );
    const costFeature = devices[0].features.find(
      (f) => f.type === DEVICE_FEATURE_TYPES.ENERGY_SENSOR.THIRTY_MINUTES_CONSUMPTION_COST,
    );
    expect(consumptionFeature).to.not.equal(undefined);
    expect(costFeature).to.not.equal(undefined);
    expect(consumptionFeature.id).to.equal('consumption-feature-id');
    expect(costFeature.id).to.equal('cost-feature-id');
  });

  it('should mark device as updatable when a real feature is added', async () => {
    // PREPARE
    // Existing device has 2 features
    const existingDevice = {
      id: 'existing-device-id',
      external_id: 'zigbee2mqtt:0x00158d00045b2740',
      room_id: 'room_id',
      name: 'Existing Device',
      features: [
        {
          id: 'feature-1',
          external_id: 'zigbee2mqtt:0x00158d00045b2740:switch:binary:state',
          category: DEVICE_FEATURE_CATEGORIES.SWITCH,
          type: DEVICE_FEATURE_TYPES.SWITCH.BINARY,
        },
      ],
    };

    gladys.stateManager.get.returns(existingDevice);

    // New device from Zigbee2mqtt has 2 features (1 new)
    zigbee2MqttService.device.discoveredDevices = {
      '0x00158d00045b2740': {
        friendly_name: '0x00158d00045b2740',
        supported: true,
        definition: {
          model: 'Test Model',
          exposes: [
            { type: 'binary', name: 'state', property: 'state', access: 3 },
            { type: 'numeric', name: 'power', property: 'power', unit: 'W', access: 1 },
          ],
        },
      },
    };

    // EXECUTE
    const devices = zigbee2MqttService.device.getDiscoveredDevices();

    // ASSERT
    expect(devices).to.have.lengthOf(1);
    expect(devices[0].updatable).to.equal(true);
  });

  it('should mark device as updatable when a real feature is removed', async () => {
    // PREPARE
    // Existing device has 2 features
    const existingDevice = {
      id: 'existing-device-id',
      external_id: 'zigbee2mqtt:0x00158d00045b2740',
      room_id: 'room_id',
      name: 'Existing Device',
      features: [
        {
          id: 'feature-1',
          external_id: 'zigbee2mqtt:0x00158d00045b2740:switch:binary:state',
          category: DEVICE_FEATURE_CATEGORIES.SWITCH,
          type: DEVICE_FEATURE_TYPES.SWITCH.BINARY,
        },
        {
          id: 'feature-2',
          external_id: 'zigbee2mqtt:0x00158d00045b2740:switch:power:power',
          category: DEVICE_FEATURE_CATEGORIES.SWITCH,
          type: DEVICE_FEATURE_TYPES.SWITCH.POWER,
        },
      ],
    };

    gladys.stateManager.get.returns(existingDevice);

    // New device from Zigbee2mqtt has only 1 feature (power removed)
    zigbee2MqttService.device.discoveredDevices = {
      '0x00158d00045b2740': {
        friendly_name: '0x00158d00045b2740',
        supported: true,
        definition: {
          model: 'Test Model',
          exposes: [{ type: 'binary', name: 'state', property: 'state', access: 3 }],
        },
      },
    };

    // EXECUTE
    const devices = zigbee2MqttService.device.getDiscoveredDevices();

    // ASSERT
    expect(devices).to.have.lengthOf(1);
    expect(devices[0].updatable).to.equal(true);
  });
});
