const { DEVICE_FEATURE_CATEGORIES, DEVICE_FEATURE_TYPES } = require('../../../../utils/constants');

const c2cMotion = {
  value: 'c2c-motion',
  categories: {
    [DEVICE_FEATURE_CATEGORIES.MOTION_SENSOR]: [DEVICE_FEATURE_TYPES.SENSOR.BINARY],
    [DEVICE_FEATURE_CATEGORIES.BATTERY]: [DEVICE_FEATURE_TYPES.SENSOR.INTEGER],
    [DEVICE_FEATURE_CATEGORIES.TEMPERATURE_SENSOR]: [DEVICE_FEATURE_TYPES.SENSOR.DECIMAL],
  },
};

module.exports = { c2cMotion };
