const { DEVICE_FEATURE_CATEGORIES, DEVICE_FEATURE_TYPES } = require('../../../../utils/constants');

const c2cContact = {
  value: 'c2c-contact',
  categories: {
    [DEVICE_FEATURE_CATEGORIES.OPENING_SENSOR]: [DEVICE_FEATURE_TYPES.SENSOR.BINARY],
    [DEVICE_FEATURE_CATEGORIES.BATTERY]: [DEVICE_FEATURE_TYPES.SENSOR.INTEGER, DEVICE_FEATURE_TYPES.SENSOR.DECIMAL],
    [DEVICE_FEATURE_CATEGORIES.TEMPERATURE_SENSOR]: [DEVICE_FEATURE_TYPES.SENSOR.DECIMAL],
  },
};

module.exports = { c2cContact };
