const dps = [
  {
    id: 1,
    code: 'switch',
    type: 'boolean',
    label: 'Marche / Arrêt',
  },
  {
    id: 2,
    code: 'temp_set',
    type: 'integer',
    label: 'Température de consigne',
    min: 16,
    max: 32,
    step: 1,
    scale: 0.1,
    raw: {
      min: 160,
      max: 320,
      step: 10,
    },
    unit: 'c',
  },
  {
    id: 3,
    code: 'temp_current',
    type: 'integer',
    label: 'Température actuelle',
    min: 0,
    max: 60,
    scale: 0.1,
    raw: {
      min: 0,
      max: 600,
      step: 1,
    },
    unit: 'c',
  },
  {
    id: 4,
    code: 'mode',
    type: 'string',
    label: 'Mode',
    map: {
      auto: 'auto',
      cold: 'cool',
      wet: 'dry',
      heat: 'heat',
      fan: 'fan_only',
    },
  },
  {
    id: 5,
    code: 'fan_speed_enum',
    type: 'string',
    label: 'Vitesse ventilateur',
    map: {
      auto: 'auto',
      low: 'low',
      low_mid: 'low_mid',
      mid: 'mid',
      mid_high: 'mid_high',
      high: 'high',
      mute: 'mute',
      turbo: 'turbo',
    },
  },
  { id: 8, code: 'eco', type: 'boolean', label: 'Éco' },
  { id: 9, code: 'drying', type: 'boolean', label: 'Déshumidification' },
  { id: 12, code: 'heat', type: 'boolean', label: 'Chauffage auxiliaire' },
  { id: 13, code: 'light', type: 'boolean', label: 'Lumière' },
  { id: 15, code: 'sleep', type: 'boolean', label: 'Mode nuit' },
  { id: 20, code: 'countdown_left', type: 'integer', label: 'Minuteur (restant)' },
  { id: 22, code: 'countdown', type: 'integer', label: 'Minuteur' },
  { id: 105, code: 'temp_unit_convert', type: 'string', label: 'Unité température', map: { c: 'c', f: 'f' } },
  { id: 110, code: 'health', type: 'boolean', label: 'Santé' },
  { id: 111, code: 'cleaning', type: 'boolean', label: 'Auto-nettoyage' },
  { id: 112, code: 'hvac_action', type: 'string', label: 'Action HVAC' },
];

module.exports = {
  name: 'air_conditioner_mapping',
  dps,
};
