const { features } = require('../utils/features');

/**
 * Gledopto managed models.
 */
const Gledopto = {
  brand: 'Gledopto',
  models: {
    'GD-CZ-006': [features.brightness, features.light],
    'GL-B-001P': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-B-001Z': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-B-001ZS': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-B-007P': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-B-007Z': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-B-007ZS': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-B-008P': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-B-008Z': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-B-008ZS': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-C-006': [features.brightness, features.color_temperature, features.light],
    'GL-C-006P': [features.brightness, features.color_temperature, features.light],
    'GL-C-006S': [features.brightness, features.color_temperature, features.light],
    'GL-C-007-1ID': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-C-007-2ID': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-C-007P': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-C-007S': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-C-008-1ID': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-C-008-2ID': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-C-008P': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-C-008S': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-C-009': [features.brightness, features.light],
    'GL-C-009P': [features.brightness, features.light],
    'GL-C-009S': [features.brightness, features.light],
    'GL-D-003P': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-D-003Z': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-D-003ZS': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-D-004P': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-D-004Z': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-D-004ZS': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-D-005P': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-D-005Z': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-D-005ZS': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-FL-004P': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-FL-004TZ': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-FL-004TZS': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-FL-005P': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-FL-005TZ': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-FL-005TZS': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-FL-006P': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-FL-006TZ': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-FL-006TZS': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-G-001P': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-G-001Z': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-G-001ZS': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-G-007Z': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-H-001': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-MC-001': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-MC-001P': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-S-003Z': [features.brightness, features.color, features.light],
    'GL-S-004P': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-S-004Z': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-S-004ZS': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-S-005Z': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-S-007P': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-S-007Z': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-S-007ZS': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-S-008Z': [features.brightness, features.color, features.color_temperature, features.light],
    'GL-SD-001': [features.brightness, features.light],
    'GL-W-001Z': [features.switch_sensor],
  },
};

module.exports = {
  Gledopto,
};
