const { features } = require('../utils/features');

/**
 * Innr managed models.
 */
const Innr = {
  brand: 'Innr',
  models: {
    'AE 260': [features.brightness, features.light],
    'AE 280 C': [features.brightness, features.color, features.color_temperature, features.light],
    'BE 220': [features.brightness, features.light],
    'BF 263': [features.brightness, features.light],
    'BF 265': [features.brightness, features.light],
    'BY 165': [features.brightness, features.light],
    'BY 178 T': [features.brightness, features.color_temperature, features.light],
    'BY 185 C': [features.brightness, features.color, features.color_temperature, features.light],
    'BY 285 C': [features.brightness, features.color, features.color_temperature, features.light],
    'DL 110 N': [features.brightness, features.light],
    'DL 110 W': [features.brightness, features.light],
    'FL 120 C': [features.brightness, features.color, features.color_temperature, features.light],
    'FL 130 C': [features.brightness, features.color, features.color_temperature, features.light],
    'FL 140 C': [features.brightness, features.color, features.color_temperature, features.light],
    'OFL 120 C': [features.brightness, features.color, features.color_temperature, features.light],
    'OFL 140 C': [features.brightness, features.color, features.color_temperature, features.light],
    'OPL 130 C': [features.brightness, features.color, features.color_temperature, features.light],
    'OSL 130 C': [features.brightness, features.color, features.color_temperature, features.light],
    'PL 110': [features.brightness, features.light],
    'PL 115': [features.brightness, features.light],
    'RB 145': [features.brightness, features.light],
    'RB 148 T': [features.brightness, features.color_temperature, features.light],
    'RB 162': [features.brightness, features.light],
    'RB 165': [features.brightness, features.light],
    'RB 172 W': [features.brightness, features.light],
    'RB 175 W': [features.brightness, features.light],
    'RB 178 T': [features.brightness, features.color_temperature, features.light],
    'RB 185 C': [features.brightness, features.color, features.color_temperature, features.light],
    'RB 245': [features.brightness, features.light],
    'RB 248 T': [features.brightness, features.color_temperature, features.light],
    'RB 250 C': [features.brightness, features.color, features.color_temperature, features.light],
    'RB 265': [features.brightness, features.light],
    'RB 278 T': [features.brightness, features.color_temperature, features.light],
    'RB 285 C': [features.brightness, features.color, features.color_temperature, features.light],
    'RC 110': [features.button],
    'RCL 110': [features.brightness, features.light],
    'RCL 240 T': [features.brightness, features.color_temperature, features.light],
    'RF 261': [features.brightness, features.light],
    'RF 263': [features.brightness, features.light],
    'RF 264': [features.brightness, features.light],
    'RF 265': [features.brightness, features.light],
    'RS 122': [features.brightness, features.light],
    'RS 125': [features.brightness, features.light],
    'RS 128 T': [features.brightness, features.color_temperature, features.light],
    'RS 225': [features.brightness, features.light],
    'RS 226': [features.brightness, features.light],
    'RS 228 T': [features.brightness, features.color_temperature, features.light],
    'RS 229 T': [features.brightness, features.color_temperature, features.light],
    'RS 230 C': [features.brightness, features.color, features.color_temperature, features.light],
    'RSL 110': [features.brightness, features.light],
    'RSL 115': [features.brightness, features.light],
    'SL 110 M': [features.brightness, features.light],
    'SL 110 N': [features.brightness, features.light],
    'SL 110 W': [features.brightness, features.light],
    'SP 120': [features.current, features.energy, features.power, features.switch_sensor, features.voltage],
    'SP 220': [features.switch_sensor],
    'SP 222': [features.switch_sensor],
    'SP 224': [features.switch_sensor],
    'ST 110': [features.brightness, features.light],
    'UC 110': [features.brightness, features.light],
  },
};

module.exports = {
  Innr,
};
