const { features } = require('../utils/features');

/**
 * Xiaomi managed models.
 */
const Xiaomi = {
  brand: 'Xiaomi',
  models: {
    // A6121: [],
    'AAQS-S01': [features.humidity, features.temperature],
    DJT11LM: [features.button, features.voltage],
    DJT12LM: [features.button],
    GZCGQ01LM: [features.illuminance],
    GZCGQ11LM: [features.illuminance, features.voltage],
    HLQDQ01LM: [features.brightness, features.light],
    'JTQJ-BF-01LM/BW': [features.smoke],
    'JTYJ-GD-01LM/BW': [features.smoke, features.voltage],
    JWDL001A: [features.brightness, features.color_temperature, features.light],
    JWSP001A: [features.brightness, features.color_temperature, features.light],
    LLKZMK11LM: [features.energy, features.power, features.switch, features.temperature, features.voltage],
    MCCGQ01LM: [features.door, features.voltage],
    MCCGQ11LM: [features.door, features.temperature, features.voltage],
    MCCGQ12LM: [features.door, features.voltage],
    MFKZQ01LM: [features.button, features.voltage],
    QBCZ11LM: [features.energy, features.power, features.switch, features.temperature, features.voltage],
    QBCZ14LM: [
      features.current,
      features.energy,
      features.power,
      features.switch,
      features.temperature,
      features.voltage,
    ],
    QBCZ15LM: [
      features.current,
      features.energy,
      features.power,
      features.switch,
      features.temperature,
      features.voltage,
    ],
    QBKG03LM: [features.button, features.switch, features.temperature],
    QBKG04LM: [features.button, features.switch],
    QBKG11LM: [features.button, features.power, features.switch, features.temperature],
    QBKG12LM: [features.button, features.power, features.switch, features.temperature],
    QBKG21LM: [features.button, features.switch],
    QBKG22LM: [features.button, features.switch],
    QBKG23LM: [
      features.button,
      features.energy,
      features.power,
      features.switch,
      features.temperature,
      features.voltage,
    ],
    QBKG24LM: [features.button, features.power, features.switch],
    QBKG25LM: [features.button, features.switch],
    QBKG26LM: [features.button, features.power, features.switch],
    QBKG31LM: [features.button, features.power, features.switch],
    QBKG38LM: [features.button, features.switch],
    QBKG39LM: [features.button, features.switch],
    QBKG40LM: [features.button, features.switch],
    QBKG41LM: [features.button, features.switch],
    RTCGQ01LM: [features.motion, features.voltage],
    RTCGQ11LM: [features.illuminance, features.motion, features.temperature, features.voltage],
    RTCGQ12LM: [features.motion],
    RTCGQ13LM: [features.motion],
    SJCGQ11LM: [features.voltage, features.water],
    SJCGQ12LM: [features.voltage, features.water],
    'SP-EUC01': [features.energy, features.power, features.switch],
    'SRSC-M01': [features.door],
    'SSM-U01': [features.energy, features.power, features.switch],
    'SSM-U02': [features.switch],
    VOCKQJK11LM: [features.humidity, features.temperature],
    'WRS-R02': [features.button],
    'WS-EUK01': [features.button, features.switch],
    'WS-EUK02': [features.button, features.switch],
    'WS-EUK03': [features.button, features.energy, features.power, features.switch, features.temperature],
    'WS-EUK04': [features.button, features.energy, features.power, features.switch, features.temperature],
    'WS-USC01': [features.switch],
    'WS-USC02': [features.switch],
    'WS-USC03': [features.switch],
    'WS-USC04': [features.switch],
    WSDCGQ01LM: [features.humidity, features.temperature, features.voltage],
    WSDCGQ11LM: [features.humidity, features.pressure, features.temperature, features.voltage],
    WSDCGQ12LM: [features.humidity, features.pressure, features.temperature, features.voltage],
    WXCJKG11LM: [features.button],
    WXCJKG12LM: [features.button],
    WXCJKG13LM: [features.button],
    WXKG01LM: [features.button, features.voltage],
    WXKG02LM_rev1: [features.button, features.voltage],
    WXKG02LM_rev2: [features.button, features.voltage],
    WXKG03LM_rev1: [features.button, features.voltage],
    WXKG03LM_rev2: [features.button, features.voltage],
    WXKG06LM: [features.button, features.voltage],
    WXKG07LM: [features.button, features.voltage],
    WXKG11LM: [features.button, features.voltage],
    WXKG12LM: [features.button, features.voltage],
    WXKG13LM: [features.button, features.voltage],
    XDD11LM: [features.brightness, features.color_temperature, features.light],
    XDD12LM: [features.brightness, features.color_temperature, features.light],
    XDD13LM: [features.brightness, features.color_temperature, features.light],
    ZNCJMB14LM: [features.switch],
    ZNCLDJ11LM: [features.door],
    ZNCLDJ12LM: [features.door],
    ZNCZ02LM: [features.energy, features.power, features.switch, features.temperature],
    ZNCZ03LM: [features.energy, features.power, features.switch, features.temperature, features.voltage],
    ZNCZ04LM: [
      features.current,
      features.energy,
      features.power,
      features.switch,
      features.temperature,
      features.voltage,
    ],
    ZNCZ11LM: [features.energy, features.power, features.switch, features.temperature, features.voltage],
    ZNCZ12LM: [features.energy, features.power, features.switch, features.temperature, features.voltage],
    ZNCZ15LM: [
      features.current,
      features.energy,
      features.power,
      features.switch,
      features.temperature,
      features.voltage,
    ],
    ZNJLBL01LM: [features.door],
    ZNLDP12LM: [features.brightness, features.color_temperature, features.light],
    ZNMS11LM: [features.button],
    ZNMS12LM: [features.button, features.voltage],
    ZNMS13LM: [features.button],
    ZNTGMK11LM: [features.brightness, features.color, features.color_temperature, features.light],
  },
};

module.exports = {
  Xiaomi,
};
