const CONFIGURATION = {
  MQTT_URL_KEY: 'Z2M_MQTT_URL',
//  MQTT_URL_VALUE: 'mqtt://z2m-mqtt:1884',
  MQTT_URL_VALUE: 'mqtt://localhost:1884',
  Z2M_MQTT_USERNAME_KEY: 'Z2M_MQTT_USERNAME',
  Z2M_MQTT_USERNAME_VALUE: 'z2m',
  Z2M_MQTT_PASSWORD_KEY: 'Z2M_MQTT_PASSWORD',
  GLADYS_MQTT_USERNAME_KEY: 'GLADYS_MQTT_USERNAME',
  GLADYS_MQTT_USERNAME_VALUE: 'gladys',
  GLADYS_MQTT_PASSWORD_KEY: 'GLADYS_MQTT_PASSWORD',
};

const DEFAULT = {
  TOPICS: [
    'zigbee2mqtt/#', // Default zigbee2mqtt topic
  ],
  INSTALLATION_STATUS: {
    DONE: 'DONE',
    IN_PROGRESS: 'IN_PROGRESS',
    ERROR: 'ERROR',
  },
};

module.exports = {
  CONFIGURATION,
  DEFAULT,
};
