const { mergeDevices } = require('../../../utils/device');
const { convertDevice } = require('../utils/convertDevice');
const { addEnergyFeatures } = require('../../energy-monitoring/utils/addEnergyFeatures');
const { DEVICE_FEATURE_CATEGORIES, DEVICE_FEATURE_TYPES } = require('../../../utils/constants');

/**
 * @description Get discovered devices.
 * @param {object} filters - Filters to apply.
 * @param {string} defaultElectricMeterDeviceFeatureId - Default electric meter device feature ID.
 * @returns {Array} Array of discovered devices.
 * @example
 * getDiscoveredDevices();
 */
function getDiscoveredDevices(filters = {}, defaultElectricMeterDeviceFeatureId) {
  let devices = Object.values(this.discoveredDevices)
    // Filter unknown models
    .filter((d) => d.definition !== null)
    // Convert to Gladys device
    .map((d) => convertDevice(d, this.serviceId))
    .map((d) => {
      // Remove features with duplicate external_id
      // This code is needed because AQARA motion sensor
      // Returns 2 illuminance features and it doesn't work with Gladys
      d.features = d.features.reduce((acc, current) => {
        const isDuplicate = acc.some((feature) => feature.external_id === current.external_id);
        if (!isDuplicate) {
          acc.push(current);
        }
        return acc;
      }, []);

      return d;
    })
    .map((d) => {
      const existingDevice = this.gladys.stateManager.get('deviceByExternalId', d.external_id);
      // Add existing energy consumption/cost features to the new device before merge
      // so that mergeDevices can properly compare feature counts.
      // These features are generated by Gladys (not from Zigbee2mqtt) so they won't be in the new device.
      if (existingDevice && existingDevice.features) {
        existingDevice.features.forEach((existingFeature) => {
          const isEnergyConsumptionOrCost =
            existingFeature.category === DEVICE_FEATURE_CATEGORIES.ENERGY_SENSOR &&
            (existingFeature.type === DEVICE_FEATURE_TYPES.ENERGY_SENSOR.THIRTY_MINUTES_CONSUMPTION ||
              existingFeature.type === DEVICE_FEATURE_TYPES.ENERGY_SENSOR.THIRTY_MINUTES_CONSUMPTION_COST);
          if (isEnergyConsumptionOrCost) {
            // Only preserve this child feature if its parent meter still exists in the new device
            const parentStillExists = existingFeature.energy_parent_id
              ? d.features.some((f) => f.id === existingFeature.energy_parent_id) ||
                existingDevice.features.some(
                  (f) =>
                    f.id === existingFeature.energy_parent_id &&
                    d.features.some((nf) => nf.external_id === f.external_id),
                )
              : false;
            if (parentStillExists) {
              const alreadyExists = d.features.some((f) => f.external_id === existingFeature.external_id);
              if (!alreadyExists) {
                // Clone the feature to avoid mutating the cached object
                d.features.push({ ...existingFeature });
              }
            }
          }
        });
      }
      // Also copy existing params (like ENERGY_INDEX_LAST_PROCESSED) to the new device
      // These params are added by Gladys energy monitoring, not from Zigbee2mqtt
      if (existingDevice && existingDevice.params && existingDevice.params.length > 0) {
        if (!d.params) {
          d.params = [];
        }
        existingDevice.params.forEach((existingParam) => {
          const alreadyExists = d.params.some((p) => p.name === existingParam.name);
          if (!alreadyExists) {
            d.params.push(existingParam);
          }
        });
      }
      // Merge with existing device.
      return mergeDevices(d, existingDevice);
    })
    .map((d) => {
      // Add energy features after merge so we can find existing consumption/cost features
      addEnergyFeatures(d, defaultElectricMeterDeviceFeatureId);
      return d;
    });

  const { filter_existing: filterExisting } = filters;
  if (`${filterExisting}` === 'true') {
    devices = devices.filter((device) => device.id === undefined || device.updatable);
  }

  return devices;
}

module.exports = {
  getDiscoveredDevices,
};
