const {
  DEVICE_FEATURE_CATEGORIES,
  DEVICE_FEATURE_TYPES,
  DEVICE_FEATURE_UNITS,
} = require('../../../../utils/constants');

const CONFIGURATION = {
  NETATMO_CLIENT_ID: 'NETATMO_CLIENT_ID',
  NETATMO_CLIENT_SECRET: 'NETATMO_CLIENT_SECRET',
  NETATMO_USERNAME: 'NETATMO_USERNAME',
  NETATMO_PASSWORD: 'NETATMO_PASSWORD',
  NETATMO_IS_CONNECT: 'NETATMO_IS_CONNECT',
};

const DEFAULT = {
  TOPICS: [
    'gladys/master/#', // Default gladys topic
  ],
};

const NETATMO_VALUES = {
  UNITS: {
    SYSTEM: {
      TEMPERATURE: {
        0: 'celsius',
        1: 'fahrenheit',
      },
      DISTANCE: {
        0: 'millimeter',
        1: 'inch',
      },
      PRECIPITATION: {
        0: 'millimeter-hour',
        1: 'inch-hour',
      },
    },
    WIND: {
      0: 'kilometer-hour',
      1: 'miles-hour',
      2: 'meter-second',
      3: 'beaufort',
      4: 'knots',
    },
    PRESSURE: {
      0: 'millibar',
      1: 'inch-mercury',
      2: 'millimeter-mercury',
    },
    FEEL_LIKE_ALGO: {
      0: 'Based on Humidex',
      1: 'Based on heat index',
    },
  },
  BATTERY: {
    VERY_LOW: 5,
    LOW: 25,
    MEDIUM: 50,
    HIGH: 75,
    FULL: 100,
  },
  SECURITY: {
    STATUS: {
      OFF: 0,
      ON: 1,
    },
    LIGHT: {
      OFF: 0,
      ON: 1,
      AUTO: 2,
    },
    SIREN: {
      NO_NEWS: -1,
      NO_SOUND: 0,
      SOUND: 1,
      WARNING: 2,
    },
    DOOR_TAG: {
      UNDEFINED: -1,
      CLOSED: 0,
      OPEN: 1,
    },
  },
  ENERGY: {
    SETPOINT_MODE: {
      SCHEDULE: 0,
      MANUAL: 1,
      HG: 2, // Hors Gel
      AWAY: 3, // Absent
      PROGRAM: 0,
    },
    HEATING_REQ: {
      0: 0,
      100: 1,
    },
  },
};

const DEVICE_FEATURE_TYPES_BY_CATEGORY = {
  [DEVICE_FEATURE_CATEGORIES.INDEX]: [DEVICE_FEATURE_TYPES.INDEX.INTEGER, DEVICE_FEATURE_TYPES.INDEX.DIMMER],
  [DEVICE_FEATURE_CATEGORIES.ANGLE_SENSOR]: [DEVICE_FEATURE_TYPES.SENSOR.STRING, DEVICE_FEATURE_TYPES.SENSOR.DECIMAL],
};

const DEVICE_FEATURE_UNITS_BY_CATEGORY_TYPES = {
  [DEVICE_FEATURE_TYPES.BATTERY.INTEGER]: {
    [DEVICE_FEATURE_CATEGORIES.BATTERY]: [DEVICE_FEATURE_UNITS.PERCENT],
  },
  [DEVICE_FEATURE_TYPES.SETPOINT.DECIMAL]: {
    [DEVICE_FEATURE_CATEGORIES.SETPOINT]: [DEVICE_FEATURE_UNITS.CELSIUS, DEVICE_FEATURE_UNITS.FAHRENHEIT],
  },
  [DEVICE_FEATURE_TYPES.SENSOR.DECIMAL]: {
    [DEVICE_FEATURE_CATEGORIES.CO2_SENSOR]: [DEVICE_FEATURE_UNITS.PPM, DEVICE_FEATURE_UNITS.PERCENT],
    [DEVICE_FEATURE_CATEGORIES.DISTANCE_SENSOR]: [
      DEVICE_FEATURE_UNITS.INCH,
      DEVICE_FEATURE_UNITS.MILLIMETER,
      DEVICE_FEATURE_UNITS.CENTIMETER,
    ],
    [DEVICE_FEATURE_CATEGORIES.HUMIDITY_SENSOR]: [DEVICE_FEATURE_UNITS.PERCENT],
    [DEVICE_FEATURE_CATEGORIES.LIGHT_SENSOR]: [DEVICE_FEATURE_UNITS.LUX],
    [DEVICE_FEATURE_CATEGORIES.PRESSURE_SENSOR]: [
      DEVICE_FEATURE_UNITS.PASCAL,
      DEVICE_FEATURE_UNITS.MILLIBAR,
      DEVICE_FEATURE_UNITS.INCH_MERCURY,
      DEVICE_FEATURE_UNITS.MILLIMETER_MERCURY,
    ],
    [DEVICE_FEATURE_CATEGORIES.TEMPERATURE_SENSOR]: [DEVICE_FEATURE_UNITS.CELSIUS, DEVICE_FEATURE_UNITS.FAHRENHEIT],
    [DEVICE_FEATURE_CATEGORIES.WINDSPEED_SENSOR]: [
      DEVICE_FEATURE_UNITS.KILOMETER_HOUR,
      DEVICE_FEATURE_UNITS.MILES_HOUR,
      DEVICE_FEATURE_UNITS.METER_SECOND,
      DEVICE_FEATURE_UNITS.BEAUFORT,
      DEVICE_FEATURE_UNITS.KNOTS,
    ],
    [DEVICE_FEATURE_CATEGORIES.RAINFALL_SENSOR]: [
      DEVICE_FEATURE_UNITS.INCH,
      DEVICE_FEATURE_UNITS.INCH_HOUR,
      DEVICE_FEATURE_UNITS.MILLIMETER,
      DEVICE_FEATURE_UNITS.MILLIMETER_HOUR,
    ],
    [DEVICE_FEATURE_CATEGORIES.ANGLE_SENSOR]: [DEVICE_FEATURE_UNITS.DEGREE],
    [DEVICE_FEATURE_CATEGORIES.NOISE_SENSOR]: [DEVICE_FEATURE_UNITS.DECIBEL],
  },
  [DEVICE_FEATURE_TYPES.SENSOR.INTEGER]: {
    [DEVICE_FEATURE_CATEGORIES.LIGHT_SENSOR]: [DEVICE_FEATURE_UNITS.LUX],
    [DEVICE_FEATURE_CATEGORIES.PRESSURE_SENSOR]: [
      DEVICE_FEATURE_UNITS.PASCAL,
      DEVICE_FEATURE_UNITS.MILLIBAR,
      DEVICE_FEATURE_UNITS.INCH_MERCURY,
      DEVICE_FEATURE_UNITS.MILLIMETER_MERCURY,
    ],
    [DEVICE_FEATURE_CATEGORIES.WINDSPEED_SENSOR]: [
      DEVICE_FEATURE_UNITS.KILOMETER_HOUR,
      DEVICE_FEATURE_UNITS.MILES_HOUR,
      DEVICE_FEATURE_UNITS.METER_SECOND,
      DEVICE_FEATURE_UNITS.BEAUFORT,
      DEVICE_FEATURE_UNITS.KNOTS,
    ],
    [DEVICE_FEATURE_CATEGORIES.ANGLE_SENSOR]: [DEVICE_FEATURE_UNITS.DEGREE],
    [DEVICE_FEATURE_CATEGORIES.NOISE_SENSOR]: [DEVICE_FEATURE_UNITS.DECIBEL],
  },
  [DEVICE_FEATURE_TYPES.SWITCH.POWER]: {
    [DEVICE_FEATURE_CATEGORIES.SWITCH]: [DEVICE_FEATURE_UNITS.WATT, DEVICE_FEATURE_UNITS.KILOWATT],
  },
  [DEVICE_FEATURE_TYPES.SWITCH.ENERGY]: {
    [DEVICE_FEATURE_CATEGORIES.SWITCH]: [DEVICE_FEATURE_UNITS.KILOWATT_HOUR],
  },
  [DEVICE_FEATURE_TYPES.SWITCH.VOLTAGE]: {
    [DEVICE_FEATURE_CATEGORIES.SWITCH]: [DEVICE_FEATURE_UNITS.VOLT],
  },
  [DEVICE_FEATURE_TYPES.SWITCH.CURRENT]: {
    [DEVICE_FEATURE_CATEGORIES.SWITCH]: [DEVICE_FEATURE_UNITS.AMPERE],
  },
};

module.exports = {
  CONFIGURATION,
  DEFAULT,
  NETATMO_VALUES,

  DEVICE_FEATURE_TYPES_BY_CATEGORY,
  DEVICE_FEATURE_UNITS_BY_CATEGORY_TYPES,
};
