const CONFIGURATION_KEYS = {
  APPLICATION_ID: 'APPLICATION_ID',
  APPLICATION_SECRET: 'APPLICATION_SECRET',
  APPLICATION_REGION: 'APPLICATION_REGION',
  USER_TOKENS: 'USER_TOKENS',
};

const DEVICE_SERVICE_ID = 'ewelink';
const DEVICE_EXTERNAL_ID_BASE = 'ewelink';

const DEVICE_IP_ADDRESS = 'IP_ADDRESS';
const DEVICE_FIRMWARE = 'FIRMWARE';
const DEVICE_ONLINE = 'ONLINE';

const NB_MAX_RETRY_EXPIRED = 1;

module.exports = {
  CONFIGURATION_KEYS,
  DEVICE_SERVICE_ID,
  DEVICE_EXTERNAL_ID_BASE,
  DEVICE_IP_ADDRESS,
  DEVICE_FIRMWARE,
  DEVICE_ONLINE,
  NB_MAX_RETRY_EXPIRED,
};
