export const WithingsDeviceImgByModel = {
  'Kid Scale': 'KidScale.jpg',
  WBS08: 'body-cardio-black-kg.jpg',
  WBS10: 'body-cardio-black-kg.jpg',
  WBS11: 'body-cardio-black-kg.jpg',
  WS30: 'body-cardio-black-kg.jpg',
  'Smart Body Analyzer': 'body-cardio-black-kg.jpg',
  'Withings WBS01': 'body-plus-black-kg.jpg',
  'Body+': 'body-plus-black-kg.jpg',
  'Body Cardio': 'body-cardio-black-kg.jpg',
  Body: 'body-black-kg.jpg',
  'Smart Baby Monitor': 'SmartBabyMonitor.jpg',
  'Withings Home': 'home.jpg',
  'Withings Blood Pressure Monitor V1': 'bpm-connect.jpg',
  'Withings Blood Pressure Monitor V2': 'bpm-connect.jpg',
  'Withings Blood Pressure Monitor V3': 'bpm-connect.jpg',
  'BPM Core': 'bpm-core.jpg',
  'BPM Connect': 'bpm-connect.jpg',
  'BPM Connect Pro': 'bpm-connect.jpg',
  Pulse: 'pulse-hr-black.jpg',
  Activite: 'go.jpg',
  'Activite (Pop: Steel)': 'steel-white.jpg',
  'Withings Go': 'go.jpg',
  'Activite Steel HR': 'steel-hr-36b.jpg',
  'Activite Steel HR Sport Edition': 'steel-hr-sport-40b.jpg',
  'Pulse HR': 'pulse-hr-black.jpg',
  Move: 'move-ecg-white-kg.jpg',
  'Move ECG': 'move-ecg-white-kg.jpg',
  'Aura Dock': 'Aura_2.jpg',
  'Aura Sensor': 'Aura_2.jpg',
  'Aura Sensor V2': 'Aura_2.jpg',
  Thermo: 'thermo-c.jpg'
};
