const CONFIGURATION = {
  INFLUXDB_URL: 'INFLUXDB_URL',
  INFLUXDB_TOKEN: 'INFLUXDB_TOKEN',
  INFLUXDB_ORG: 'INFLUXDB_ORG',
  INFLUXDB_BUCKET: 'INFLUXDB_BUCKET',
};

module.exports = {
  CONFIGURATION,
};
