const OAUTH2 = {
  VARIABLE: {
    CLIENT_ID: 'OAUTH2_CLIENT_ID',
    CLIENT_SECRET: 'OAUTH2_CLIENT_SECRET',
    ACCESS_TOKEN: 'OAUTH2_ACCESS_TOKEN',
    TOKEN_HOST: 'OAUTH2_TOKEN_HOST',
    TOKEN_PATH: 'OAUTH2_TOKEN_PATH',
    AUTHORIZE_HOST: 'OAUTH2_AUTHORIZE_HOST',
    AUTHORIZE_PATH: 'OAUTH2_AUTHORIZE_PATH',
    ADDITIONAL_ACCESS_TOKEN_REQUEST_ACTION_PARAM: 'OAUTH2_ADDITIONAL_ACCESS_TOKEN_REQUEST_ACTION_PARAM',
    INTEGRATION_SCOPE: 'OAUTH2_INTEGRATION_SCOPE',
    GRANT_TYPE: 'OAUTH2_GRANT_TYPE',
    REDIRECT_URI_SUFFIX: 'OAUTH2_REDIRECT_URI_SUFFIX',
  },
};

module.exports.OAUTH2 = OAUTH2;
