const VARIABLES = {
  GOOGLEACTIONS_USER: 'GOOGLEACTIONS_USER',
  GOOGLEACTIONS_PROJECT_KEY: 'GOOGLEACTIONS_PROJECT_KEY',
  GOOGLEACTIONS_OAUTH_CLIENT_ID: 'google-actions',
};

module.exports = {
  VARIABLES,
};
