const { DEVICE_FEATURE_CATEGORIES, DEVICE_FEATURE_TYPES } = require('../../../utils/constants');

const sensorFeatures = [
  DEVICE_FEATURE_CATEGORIES.AIRQUALITY_SENSOR,
  DEVICE_FEATURE_CATEGORIES.ANGLE_SENSOR,
  DEVICE_FEATURE_CATEGORIES.CO_SENSOR,
  DEVICE_FEATURE_CATEGORIES.CO2_SENSOR,
  DEVICE_FEATURE_CATEGORIES.DISTANCE_SENSOR,
  DEVICE_FEATURE_CATEGORIES.ENERGY_SENSOR,
  DEVICE_FEATURE_CATEGORIES.HUMIDITY_SENSOR,
  DEVICE_FEATURE_CATEGORIES.LEAK_SENSOR,
  DEVICE_FEATURE_CATEGORIES.LEVEL_SENSOR,
  DEVICE_FEATURE_CATEGORIES.LIGHT_SENSOR,
  DEVICE_FEATURE_CATEGORIES.MOTION_SENSOR,
  DEVICE_FEATURE_CATEGORIES.OPENING_SENSOR,
  DEVICE_FEATURE_CATEGORIES.PM10_SENSOR,
  DEVICE_FEATURE_CATEGORIES.PM25_SENSOR,
  DEVICE_FEATURE_CATEGORIES.FORMALDEHYD_SENSOR,
  DEVICE_FEATURE_CATEGORIES.PRECIPITATION_SENSOR,
  DEVICE_FEATURE_CATEGORIES.PRESENCE_SENSOR,
  DEVICE_FEATURE_CATEGORIES.PRESSURE_SENSOR,
  DEVICE_FEATURE_CATEGORIES.RAIN_SENSOR,
  DEVICE_FEATURE_CATEGORIES.SMOKE_SENSOR,
  DEVICE_FEATURE_CATEGORIES.TEMPERATURE_SENSOR,
  DEVICE_FEATURE_CATEGORIES.VOC_SENSOR,
  DEVICE_FEATURE_CATEGORIES.VOLUME_SENSOR,
  `${DEVICE_FEATURE_CATEGORIES.SWITCH}:${DEVICE_FEATURE_TYPES.SWITCH.POWER}`,
  `${DEVICE_FEATURE_CATEGORIES.SWITCH}:${DEVICE_FEATURE_TYPES.SWITCH.ENERGY}`,
];

const isSensorFeature = (deviceFeature) => {
  return sensorFeatures.some((types) => `${deviceFeature.category}:${deviceFeature.type}`.startsWith(types));
};

const switchableFeatures = [
  DEVICE_FEATURE_CATEGORIES.LIGHT,
  DEVICE_FEATURE_CATEGORIES.SWITCH,
  DEVICE_FEATURE_CATEGORIES.AIR_CONDITIONING,
];

const isSwitchableFeature = (deviceFeature) => {
  return switchableFeatures.some((types) =>
    `${deviceFeature.category}:${deviceFeature.type}`.startsWith(`${types}:binary`),
  );
};

const historyFeatures = [
  DEVICE_FEATURE_CATEGORIES.AIRQUALITY_SENSOR,
  DEVICE_FEATURE_CATEGORIES.CO_SENSOR,
  DEVICE_FEATURE_CATEGORIES.CO2_SENSOR,
  DEVICE_FEATURE_CATEGORIES.HUMIDITY_SENSOR,
  DEVICE_FEATURE_CATEGORIES.LIGHT_SENSOR,
  DEVICE_FEATURE_CATEGORIES.MOTION_SENSOR,
  DEVICE_FEATURE_CATEGORIES.PM10_SENSOR,
  DEVICE_FEATURE_CATEGORIES.PM25_SENSOR,
  DEVICE_FEATURE_CATEGORIES.FORMALDEHYD_SENSOR,
  DEVICE_FEATURE_CATEGORIES.PRECIPITATION_SENSOR,
  DEVICE_FEATURE_CATEGORIES.PRESENCE_SENSOR,
  DEVICE_FEATURE_CATEGORIES.PRESSURE_SENSOR,
  DEVICE_FEATURE_CATEGORIES.RAIN_SENSOR,
  DEVICE_FEATURE_CATEGORIES.SMOKE_SENSOR,
  DEVICE_FEATURE_CATEGORIES.TEMPERATURE_SENSOR,
  DEVICE_FEATURE_CATEGORIES.VOC_SENSOR,
  DEVICE_FEATURE_CATEGORIES.VOLUME_SENSOR,
  `${DEVICE_FEATURE_CATEGORIES.ENERGY_SENSOR}:${DEVICE_FEATURE_TYPES.ENERGY_SENSOR.POWER}`,
  `${DEVICE_FEATURE_CATEGORIES.ENERGY_SENSOR}:${DEVICE_FEATURE_TYPES.ENERGY_SENSOR.ENERGY}`,
  `${DEVICE_FEATURE_CATEGORIES.ENERGY_SENSOR}:${DEVICE_FEATURE_TYPES.ENERGY_SENSOR.VOLTAGE}`,
  `${DEVICE_FEATURE_CATEGORIES.ENERGY_SENSOR}:${DEVICE_FEATURE_TYPES.ENERGY_SENSOR.CURRENT}`,
  `${DEVICE_FEATURE_CATEGORIES.ENERGY_SENSOR}:${DEVICE_FEATURE_TYPES.ENERGY_SENSOR.INDEX}`,
  `${DEVICE_FEATURE_CATEGORIES.ENERGY_SENSOR}:${DEVICE_FEATURE_TYPES.ENERGY_SENSOR.DAILY_CONSUMPTION}`,
  `${DEVICE_FEATURE_CATEGORIES.SWITCH}:${DEVICE_FEATURE_TYPES.SWITCH.POWER}`,
  `${DEVICE_FEATURE_CATEGORIES.SWITCH}:${DEVICE_FEATURE_TYPES.SWITCH.ENERGY}`,
  `${DEVICE_FEATURE_CATEGORIES.SWITCH}:${DEVICE_FEATURE_TYPES.SWITCH.VOLTAGE}`,
  `${DEVICE_FEATURE_CATEGORIES.SWITCH}:${DEVICE_FEATURE_TYPES.SWITCH.CURRENT}`,
];

const isHistoryFeature = (deviceFeature) => {
  return historyFeatures.some(
    (types) =>
      `${deviceFeature.category}:${deviceFeature.type}`.startsWith(types) && deviceFeature.keep_history === true,
  );
};

module.exports = {
  isSensorFeature,
  isSwitchableFeature,
  isHistoryFeature,
};
