const CONFIG_KEYS = {
  DECONZ: 'deconz',
  EMBER: 'ember',
  EZSP: 'ezsp',
  ZSTACK: 'zstack',
};

const ADAPTERS_BY_CONFIG_KEY = {
  [CONFIG_KEYS.DECONZ]: ['ConBee', 'ConBee II', 'RaspBee', 'RaspBee II'],
  [CONFIG_KEYS.EMBER]: [
    'Aeotec Zi-Stick (ZGA008)',
    'CoolKit ZB-GW04 USB dongle (a.k.a. easyiot stick)',
    'Elelabs ELU013 and Popp ZB-STICK',
    'Elelabs Zigbee Raspberry Pi Shield/Popp ZB-Shield',
    'Home Assistant Connect ZBT-1',
    'Home Assistant Connect ZBT-2',
    'Home Assistant SkyConnect (by Nabu Casa)',
    'ITead Sonoff Zigbee 3.0 USB Dongle Plus V2 model "ZBDongle-E"',
    'Nabu Casa Home Assistant Yellow',
    'Seeed Studio XIAO MG24',
    'SMLIGHT SLZB-06M',
    'SMLIGHT SLZB-06Mg24',
    'SMLIGHT SLZB-06Mg26',
    'SMLIGHT SLZB-07',
    'SMLIGHT SLZB-07mg24',
    'SMLIGHT SLZB-MR Series (MR1/MR2/MR3/MR4) MultiRadio Zigbee + Matter-over-Thread Ethernet USB POE Wi-Fi BLE LAN adapter',
    'SMLIGHT SLZB-Ultima - Multi-radio gateway for Zigbee, Thread, Z-Wave, 4G/LTE, IR, Ethernet/Wi-Fi, Voice',
    'SMLIGHT SMHUB (Essential/Premium variants)',
    'SMLIGHT SMHUB Nano Mg24',
    'SONOFF Dongle-M',
    'SONOFF Dongle-PMG24',
    'TubesZB Zigbee EFR32 pro ethernet/USB serial coordinator',
    'TubeZB EFR32 MGM24 POE',
    'Z-WAVE>ME Z-Station (EFR32MG21P)',
    'Zbgw_pro EFR32 LAN',
  ],
  [CONFIG_KEYS.EZSP]: [
    // Legacy entries — existing installations migrated to these names via Sequelize migration
    'CoolKit ZB-GW04 USB dongle (a.k.a. easyiot stick) (legacy ezsp)',
    'Elelabs ELU013 and Popp ZB-STICK (legacy ezsp)',
    'Elelabs Zigbee Raspberry Pi Shield/Popp ZB-Shield (legacy ezsp)',
    'Home Assistant SkyConnect (by Nabu Casa) (legacy ezsp)',
    'ITead Sonoff Zigbee 3.0 USB Dongle Plus V2 model "ZBDongle-E" (legacy ezsp)',
    'TubesZB Zigbee EFR32 pro ethernet/USB serial coordinator (legacy ezsp)',
  ],
  [CONFIG_KEYS.ZSTACK]: [
    "CircuitSetup's CC2652P2 USB Coordinator",
    'cod.m Zigbee CC2652P RPi Module',
    'cod.m ZigBee CC2652P2 TCP Coordinator',
    'cod.m Zigbee Coordinator CC2652P7 (CZC-1.0)',
    'cyijun OpenZ3Gateway',
    'Egony Stick V4',
    'Electrolama zig-a-zig-ah! (zzh!)',
    'Gio-dot Z-Bee Duo with CC2652P',
    'JetHome JetHub D1+',
    'JetHome JetStick Z2/ZB6UX CC2652P1',
    'Texas Instruments CC2530',
    'Texas Instruments CC2531',
    'Texas Instruments CC2538',
    'Texas Instruments CC2538 HAT',
    'Texas Instruments LAUNCHXL-CC1352P-2',
    'Texas Instruments LAUNCHXL-CC26X2R1',
    'Texas Instruments LP-CC1352P7',
    'Texas Instruments LP-CC2652R7',
    "Tube's CC2652P2 USB Coordinator",
    "Tube's Zigbee Gateways (CC2652P2 variant)",
    'SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P',
    "Slaesh's CC2652RB stick",
    'SMLIGHT CC2652P Zigbee USB Adapter SLZB-02',
    'SMLIGHT SLZB-06 Zigbee ethernet USB POE WiFi LAN adapter',
    'SMLIGHT SLZB-06p7 Zigbee Ethernet USB POE WiFi LAN adapter',
    'SMLIGHT SLZB-07p7 Zigbee USB CC2652P7 adapter',
    'SMLIGHT SLZB-MR1 MultiRadio Zigbee+Matter-over-Thread Ethernet USB POE WiFi LAN adapter',
    'SMLIGHT SLZB-MR2 MultiRadio Zigbee+Matter-over-Thread Ethernet USB POE WiFi LAN adapter',
    'SMLIGHT SLZB-MR3 MultiRadio Zigbee+Matter-over-Thread Ethernet USB POE WiFi LAN adapter',
    'SMLIGHT SLZB-Ultima - Multi-radio gateway for Zigbee, Thread, Z-Wave, 4G/LTE, IR, Ethernet/Wi-Fi, Voice',
    'SMLIGHT SMHUB (Essential/Premium variants)',
    'SMLIGHT Zigbee LAN Adapter CC2652P Model SLZB-05',
    'Vision CC2538+CC2592 Dongle(VS203)',
    'Vision CC2652 dongle',
    'XGG Gateway',
    'XGG 52PZ2MGateway',
    'ZigStar LAN Coordinator',
    'ZigStar PoE Coordinator',
    'ZigStar Stick v4',
    'ZigStar UZG-01 - Universal Zigbee Gateway',
    'ZigStar ZigiHAT PoE',
  ],
};

const ADAPTERS = Object.entries(ADAPTERS_BY_CONFIG_KEY)
  .flatMap(([configKey, labels]) => labels.map((label) => ({ label, configKey })))
  .sort((a, b) => a.label.localeCompare(b.label));

module.exports = { ADAPTERS, ADAPTERS_BY_CONFIG_KEY, CONFIG_KEYS, DEFAULT_KEY: CONFIG_KEYS.ZSTACK };
