const TP_LINK_EXTERNAL_ID_BASE = 'tp-link';
const TP_LINK_ON = 1;
const TP_LINK_OFF = 0;
const TP_LINK_IP_ADDRESS = 'TP_LINK_IP_ADDRESS';
const TP_LINK_SERIAL_NUMBER = 'TP_LINK_SERIAL_NUMBER';

module.exports = {
  TP_LINK_EXTERNAL_ID_BASE,
  TP_LINK_ON,
  TP_LINK_OFF,
  TP_LINK_IP_ADDRESS,
  TP_LINK_SERIAL_NUMBER,
};
